(function(root, factory) {
  const value = factory();
  if (typeof window === 'undefined' && typeof module === 'object' && module.exports) module.exports = value;
  else (root.WWM_LOCALES || (root.WWM_LOCALES = {})).en = value;
})(typeof globalThis !== 'undefined' ? globalThis : this, function() {
  return {
    "cats.noHouse": "Susu needs <b>Max’s House</b> to climb",
    "cats.noParcel": "Yulmu needs a <b>parcel</b> to hide behind",
    "cats.seated": "Already settled in",
    "cats.shortBoth": "Both settled in",
    "cats.shortSusu": "Susu on the roof",
    "cats.shortYulmu": "Yulmu by the parcel",
    "cats.shortRoaming": "Both in the yard",
    "cats.shortSusuRoaming": "Susu in the yard",
    "yard.future": "See you someday",
    "yard.unmet": "We haven’t met yet",
    "yard.story.colCatBed": "Susu and Yulmu stop by for a rest.",
    "yard.story.colBrook": "Two ducks drift slow circles on the water.",
    "yard.indexTitle": "Max's Yard",
    "yard.seeYardAll": "Look around the yard",
    "hood.stage.0": "Just opened",
    "hood.stage.1": "Settling in",
    "hood.stage.2": "Feels like home",
    "hood.stage.3": "Come alive",
    "hood.left": "{n} more walks",
    "hood.grew": "{name} came alive a little — {stage}",
    "hood.slotOpened": "One more spot to fill in {name}",
    "hood.backToMap": "{name} — back to the farm map",
    "hood.lockedNext": "{name} — get the blueprint on walk {lv}",
    "hood.lockedFar": "{name} comes first",
    "hood.mapHint": "Tap a yard to look around",
    "hood.mapTodo": "{n} to visit today",
    "hood.mapNext": "Next: {name}",
    "hood.grewSlot": "{name} came alive a little — one more spot to decorate",
    "hood.signPick": "Pick up {mat}",
    "hood.signDone": "✓ Tomorrow",
    "hood.signWait": "Not yet",
    "hood.signNeedHouse": "Build Max's house first",
    "hood.signNeedBowl": "Build the bowl to fill it",
    "hood.signPaint": "Paint",
    "hood.signCats": "Call",
    "hood.matGot": "{mat} +1 · {n} now",
    "hood.slotGoWalk": "Walk in {name}",
    "yardStatus.scoop": "Scoop the leaves",
    "yardStatus.brookReady": "Leaves are drifting down",
    "yardStatus.brookDone": "All the leaves are scooped",
    "hood.slotsN": "{n} spots",
    "hood.slotWhere": "{name} · empty spot",
    "hood.slotWhereTaken": "{name} · this spot",
    "hood.slotNow": "Ready to place",
    "hood.slotMaking": "In progress",
    "hood.slotNextCol": "Next small furniture",
    "hood.slotPlaced": "Placed here",
    "hood.slotTagPlaced": "Placed",
    "hood.slotTagOwn": "Place",
    "hood.slotTagBp": "Blueprint",
    "hood.slotTagReady": "Ready",
    "hood.slotTagWalk": "{n} more",
    "hood.slotTagLater": "Later",
    "hood.slotPut": "Place here",
    "hood.slotBuild": "Build",
    "hood.slotWalkBtn": "Go walk",
    "hood.slotLater": "{n} more after that",
    "hood.slotLaterSub": "Opens once the one before is made",
    "hood.slotCareLeft": "{n} more visits",
    "hood.slotTitle": "What goes here?",
    "hood.slotSwap": "Swap for {item}",
    "hood.slotEmpty": "No decorations yet",
    "hood.slotShop": "Pick from the shop",
    "hood.slotTake": "Clear",
    "hood.slotHave": "×{n}",
    "hood.slotStanding": "Standing here",
    "hood.slotReady": "Ready to place",
    "hood.slotNeedMat": "Adding treats",
    "shop.deco": "Decor",
    "shop.haveN": "{n} owned",
    "yard.indexTodo": "{n} to do today",
    "yard.seeYard": "Look around",
    "yard.howTo": "How to use",
    "yard.chooseMove": "Tap an item to move it",
    "yard.brush.grass": "Grass",
    "yard.brush.road": "Path",
    "yard.brush.brook": "Water",
    "yard.brush.fence": "Fence",
    "yard.brush.turn": "Turn",
    "yard.cat.bld": "Buildings",
    "yard.cat.floor": "Ground",
    "yard.cat.fence": "Fence",
    "yard.bldEmpty": "No buildings in the yard",
    "yard.free": "Free",
    "yard.signHouse": "Max's",
    "yard.signYard": "Max's Yard",
    "yard.bathRub": "Tap Max to make bubbles",
    "yard.replanted": "<b>Acorn replanted</b><br>Water it to grow tomorrow",
    "yard.oakMature": "The oak is fully grown!<br>Tap to plant another acorn",
    "yard.oakGrew": "The oak grew — <b>{stage}</b><br>{reward} · Water it today",
    "yard.oakStage1": "Sprout",
    "yard.oakStage2": "Young tree",
    "yard.oakStage3": "Full-grown oak",
    "yard.played": "Max brought it back! {reward}",
    "yard.planted": "Planted <b>{name}</b><br>Water it to grow tomorrow",
    "yard.cropMature": "<b>{name}</b> is fully grown!<br>Tap to harvest",
    "yard.cropGrew": "{name} grew — <b>{count} / {max}</b><br>Water it today",
    "yard.roof": "roof",
    "yard.rim": "rim",
    "yard.flowers": "flowers",
    "yard.fence": "Fence",
    "yard.hedge": "Hedge",
    "yard.nothingToPaint": "Nothing to paint yet",
    "yard.paintUnlock": "Complete <b>{level}</b> to unlock",
    "yard.sendQuestion": "What shall we send?",
    "yard.sendTip": "A thank-you gift arrives in {time}",
    "yard.cropMissing": "You need <b>{count}</b> more {name}",
    "yard.sent": "Sent <b>{count} {name}</b><br>{reward} arrives in <b>{time}</b>",
    "yard.parcelReceived": "Parcel arrived — <b>{reward}</b>",
    "yard.plantTip": "Plant and water daily to grow in three days",
    "yard.emptyAlbum": "Nothing collected yet<br>Keep walking to find little treasures",
    "yard.place": "Place",
    "yard.act": "Go",
    "yard.mealShortDone": "All fed",
    "yard.bathShortDone": "All clean",
    "yard.colors": "Colors {count}/{max}",
    "yard.foundBone": "An old buried bone! ",
    "yard.foundSomething": "Sniff… found something! ",
    "yard.clearLand": "Clear",
    "yard.landSoon": "Coming soon",
    "yard.landTip": "Clear the bushes to make room for Max",
    "yard.story.colTeddy": "Max chewed this bear's ear as a puppy.",
    "yard.story.colDisc": "Max left tooth marks all around the rim.",
    "yard.story.colSign": "Grandpa rocks; Max dozes at his feet.",
    "yard.story.colShade": "Max's name on the stand. The water is always full.",
    "yard.story.colShoeRack": "The bone always sleeps on the cushion too.",
    "yard.story.colTub": "Max always hesitates before a bath.",
    "yard.story.colDuck": "It stopped squeaking after one big bite.",
    "yard.story.colBrush": "Brushing is the only time Max sits still.",
    "yard.story.colTramp": "Max jumps highest on the third bounce.",
    "yard.story.colOak": "An acorn from the hill grew into shade.",
    "yard.story.colDig": "Max sits beside you at watering time.",
    "yard.story.colBox": "Max always knows when a gift arrives.",
    "yard.story.colPaint": "Pick up a brush and Max comes to watch.",
    "yard.story.colRbrush": "Seven colors linger on the bristles.",
    "yard.story.colPin": "The yard feels every passing breeze.",
    "yard.story.colSled": "Max would rather chase it than ride it.",
    "yard.story.colCone": "Max picked just this one to bring home.",
    "yard.story.colDipper": "Max still jumps at the first scoop of water.",
    "yard.story.colSoapBag": "When it foams, Max pokes his nose in.",
    "yard.story.colSkip": "Three skips. Max stared into the water.",
    "yard.story.colLeafBoat": "Set it afloat and Max follows to the end.",
    "yard.story.colStep": "Max always skips the second stone.",
    "yard.story.colCairn": "Brush past and the top stone falls.",
    "yard.story.colBall": "Throw it and it is back before Max.",
    "yard.story.colStick": "He fetches it. He never lets go.",
    "yard.story.colRope": "Max just watches the rope go round.",
    "yard.story.colScare": "It scares no birds. Only Max barks.",
    "yard.story.colTrowel": "Replanted right where Max dug.",
    "yard.story.colSeedBox": "Max knows the sound of the lid.",
    "yard.story.colCan": "Roll it and Max chases it to the end.",
    "yard.story.colBlanket": "Max found this blanket in the shed first.",
    "yard.story.colKey": "Max knows the sound of these keys.",
    "yard.story.colPebble": "Painted the stones Max carried home.",
    "yard.story.colPlank": "Of four colors, Max only sniffs the green.",
    "yard.story.colMarble": "They roll until Max stops them with his nose.",
    "yard.story.colWand": "Max likes it more than the cats do.",
    "yard.story.colLamp": "When it lights up, the cats gather first.",
    "yard.story.colChime": "When it rings, Max pricks up his ears.",
    "yard.story.colBalloon": "Let go of the string and Max chases it to the end.",
    "yard.story.colVane": "When the rooster turns, so does Max.",
    "yard.story.colSlipper": "The other one is still missing.",
    "yard.story.colTwig": "Fished out of the stream, drying in the yard.",
    "yard.story.colTennis": "No idea whose. It is Max's now.",
    "yard.story.colCarrot": "He insists he fetched it, not pulled it.",
    "yard.story.colTape": "Stuck to his teeth for a good while.",
    "yard.story.colSock": "We agreed not to ask whose clothesline.",
    "yard.story.colCatBell": "The cat was glad the collar got lighter.",
    "yard.story.colSeed": "Half of it blew away on the way home.",
    "yard.story.colFlag": "A flag brought back from the hilltop.",
    "yard.story.signYard": "Max always looks back at this sign.",
    "yard.story.flower": "Max stops for a sniff, then moves on.",
    "yard.story.bowl": "The first stop after every walk.",
    "yard.story.basket": "Max won't share a single ball.",
    "yard.story.tree": "Just enough shade for one little Max.",
    "yard.story.bench": "Room enough to sit beside Max.",
    "yard.story.house": "Naps are best in the middle of the yard.",
    "yard.story.tree2": "Flowers bloom here even out of season.",
    "yard.story.mailbox": "Max is the first to notice a delivery.",
    "yard.story.pond": "Max only dips paws in for now.",
    "yard.story.swing": "Max barks when it swings on its own.",
    "common.receive": "Collect",
    "common.open": "Open",
    "full.five": "Bowls ×5",
    "full.ten": "Bowls ×10",
    "full.halfDesc": "Refills 5 bowls",
    "full.fullDesc": "Refills 10 bowls",
    "full.halfStarted": "5 bowls refilled!",
    "full.started": "10 bowls refilled!",
    "full.bought": "10 bowls refilled!",
    "full.remaining": "Full for {time}",
    "cats.both": "Susu on the roof · Yulmu by the parcel",
    "cats.susu": "Susu on the roof · Yulmu is exploring",
    "cats.yulmu": "Yulmu by the parcel · Susu is exploring",
    "cats.roaming": "Both cats are exploring",
    "cats.susuRoaming": "Susu is exploring",
    "tutorial.firstDistrict": "Shall we open <b>Max’s Yard</b>?",
    "tutorial.firstGo": "Tap <b>Go for a walk</b><br>to start your first walk",
    "tutorial.otherBall": "Tap each of the other balls, too",
    "stamp.acorns": "{count} treats",
    "stamp.hint": "{count} commands",
    "stamp.parcel": "Parcel",
    "stamp.week": "A week of walks together",
    "stamp.day": "Walk day {day}",
    "stamp.dayShort": "Day {day}",
    "stamp.today": "Today",
    "stamp.progress": "{day} / {max}",
    "stamp.secret": "Still a secret",
    "stamp.opensIn": "Opens in {count} days",
    "stamp.reward": "Today: <b>{item}</b>",
    "stamp.claimed": "Today’s gift collected",
    "stamp.open": "Open",
    "stamp.title": "Grandpa’s Gifts",
    "stamp.sceneAlt": "Grandpa gives Max a present",
    "stamp.inspect": "Tap a gift to see what it is",
    "stamp.hintGift": "×1",
    "stamp.nth": "Day {day}",
    "stamp.parcelGift": "1 full feed bag · 1 Order Ticket · 10 treats",
    "stamp.parcelLock": "Opens when all {max} are stamped",
    "yard.stoodHere": "<b>{item}</b> now stands in the yard",
    "yard.placePrompt": "Where shall we put <b>{item}</b>?<br>Tap a spot in the yard.",
    "yard.decorateDone": "🔨 Done Decorating",
    "yard.levelsUntil": "{count} levels to {item}",
    "tutorial.bf1": "Push the ball the butterfly sits on",
    "tutorial.bf1sub": "Push toward the arrow",
    "tutorial.bf2": "Nice! The butterfly moves to the next ball",
    "tutorial.bf3": "The butterfly got lost",
    "tutorial.bf3sub": "Undo one move and it will guide you again",
    "tutorial.offPath": "That was the <b>wrong way</b>.",
    "tutorial.undo": "Tap <b>Undo</b> to go back.",
    "tutorial.stuck": "That ball is stuck by the wall.<br>Tap <b>Undo</b> to go back.",
    "tutorial.help": "Find <b>?</b> inside <b>⚙</b><br>to see these tips again.",
    "hud.walk": "WALK",
    "fx.good1": "Good boy!",
    "fx.good2": "Nice!",
    "fx.good3": "There!",
    "fx.good4": "Amazing!",
    "fx.yum": "Yum!",
    "fx.allTreats": "Got them all!",
        "fx.streak": "{n} in a row, first try!",
    "tutorial.bath1": "Max is in the tub.<br>Time for some <b>bubbles</b>!",
    "tutorial.bath2": "<b>Tap Max a few times.</b><br>Fill the bubbles to get him clean.",
    "tutorial.paint1": "Your paint stand is here!<br><b>Repaint</b> things in the yard.",
    "tutorial.paint2": "<b>Tap</b> the stand.<br>Change colors anytime, <b>for free</b>.",
    "tutorial.box1": "Your harvest is ready.<br>Pack it up and <b>send it off</b>!",
    "tutorial.box2": "<b>Tap</b> the box to send it.<br>A thank-you gift arrives <b>tomorrow</b>.",
    "tutorial.oak1": "Your oak is planted.<br><b>Water</b> it once a day to help it grow.",
    "tutorial.oak2": "<b>Tap</b> the oak to water it.<br>It grows and drops acorns <b>tomorrow</b>.",
    "tutorial.meal1": "Max is <b>hungry</b>.<br>Fill his food bowl.",
    "tutorial.meal2": "<b>Tap the empty bowl.</b><br>Max will eat right away.",
    "tutorial.meal3": "These <b>dots</b> show<br>today’s meals.",
    "tutorial.toggle": "Turn your hint <b>on or off</b> here.",
    "tutorial.first": "Tap here for<br>your <b>first walk</b>!",
    "tutorial.goWalk": "Let’s walk",
    "tutorial.goShop": "Take a look",
    "tutorial.goYard": "Visit yard",
    "tutorial.viewYard": "View yard",
    "tutorial.shopOpen": "<b>Grandpa’s gift</b> has arrived!<br>See your gift and other useful items.",
    "tutorial.yardOpen": "The <b>yard</b> is open!",
    "tutorial.noteOpen": "Your <b>notebook</b> is open!",
    "tutorial.goNote": "Open notebook",
    "tutorial.noteBp": "Keep every treat and the blueprint is ready",
    "tutorial.noteBuildFirst": "The <b>blueprint</b> is ready<br>You can build it in the yard",
    "tutorial.noteBuild": "The <b>blueprint</b> is ready<br>Draw it with the pencil",
    "tutorial.errandOpen": "<b>Morning errands</b> are here!",
    "tutorial.goErrand": "See errands",
    "tutorial.activate": "Your <b>commands left</b><br>show up here",
    "tutorial.turnOn": "Turn on",
    "tutorial.practice": "Practice",
    "tutorial.practice1": "Press Max and drag him<br>all the way to the cushion!",
    "tutorial.dragOnly": "Press and hold Max,<br>then drag him to the cushion.",
    "tutorial.practice2": "It’s Max’s favorite ball!<br>Push it onto the cushion.",
    "tutorial.practice3": "Max can push.<br>He can’t pull.",
    "tutorial.practiceDone": "Ready for your first real walk?",
    "tutorial.hintSniff": "Push the bush where the squirrel sits to get the acorn.",
    "tutorial.hintDest": "Push the fence where the sparrow sits to get the acorn.",
    "tutorial.hintOrder": "Push the ball the butterfly sits on.",
    "tutorial.giftStood": "{item} now stands in your yard!",
    "tutorial.gift": "You can place {item} in your yard!",
    "tutorial.firstGift": "The yard is open!\n{gift}",
    "yard.item.flower": "Flower Bed",
    "yard.item.bowl": "Water Bowl",
    "yard.item.basket": "Ball Basket",
    "yard.item.tree": "Tree",
    "yard.item.bench": "Bench",
    "yard.more": "More",
    "yard.item.house": "Max’s House",
    "yard.item.tree2": "Blossom Tree",
    "yard.item.mailbox": "Mailbox",
    "yard.item.pond": "Pond",
    "yard.item.swing": "Swing",
    "yard.item.colTeddy": "Teddy Bear",
    "yard.item.colDisc": "Flying Disc",
    "yard.item.colSign": "Grandpa's rocking chair",
    "yard.item.colShade": "Food & water bowls",
    "yard.item.colShoeRack": "Max's cushion",
    "yard.item.colTub": "Water Tower",
    "yard.item.colDuck": "Rubber Duck",
    "yard.item.colBrush": "Grooming Brush",
    "yard.item.colOak": "Oak Tree",
    "yard.item.colDig": "Polytunnel",
    "yard.item.colTramp": "Jump Platform",
    "yard.item.colBox": "Delivery Shed",
    "yard.item.colPaint": "Paint Shed",
    "yard.item.colCatBed": "Cat Cafe",
    "yard.item.colBrook": "Duck House",
    "yard.item.colPin": "Windmill",
    "yard.item.colRbrush": "Rainbow Brush",
    "yard.item.colSled": "Sled",
    "yard.item.colCone": "Pine Cone",
    "yard.item.colDipper": "Tin Dipper",
    "yard.item.colSoapBag": "Soap Pouch",
    "yard.item.colSkip": "Skipping Stone",
    "yard.item.colLeafBoat": "Leaf Boat",
    "yard.item.colStep": "Stepping Stone",
    "yard.item.colCairn": "Stone Stack",
    "yard.item.colBall": "Rubber Ball",
    "yard.item.colStick": "Fetch Stick",
    "yard.item.colRope": "Jump Rope",
    "yard.item.colScare": "Scarecrow",
    "yard.item.colTrowel": "Trowel",
    "yard.item.colSeedBox": "Seed Box",
    "yard.item.colCan": "Tin Can Toy",
    "yard.item.colBlanket": "Old Blanket",
    "yard.item.colKey": "Shed Key",
    "yard.item.colPebble": "Painted Pebbles",
    "yard.item.colPlank": "Painted Sign",
    "yard.item.colMarble": "Marbles",
    "yard.item.colWand": "Cat Wand",
    "yard.item.colLamp": "Alley Lamp",
    "yard.item.colChime": "Wind Chime",
    "yard.item.colBalloon": "Wind Balloon",
    "yard.item.colVane": "Weather Rooster",
    "yard.item.colSlipper": "One Slipper",
    "yard.item.colTwig": "Wet Twig",
    "yard.item.colTennis": "Squashed Tennis Ball",
    "yard.item.colCarrot": "Carrot",
    "yard.item.colTape": "Packing Tape",
    "yard.item.colSock": "Painty Sock",
    "yard.item.colCatBell": "Cat Bell",
    "yard.item.colSeed": "Dandelion Seed",
    "yard.item.colFlag": "Hilltop Flag",
    "yard.item.signYard": "Max’s Yard Sign",
    "victory.goalStages": "<b>{count} stages</b> to {item}",
    "victory.goalStage": "<b>{count} stage</b> to {item}",
    "victory.goalStars": "<b>{count}</b> more treats to {item}",
    "victory.goalAcorns": "<b>{count} treats</b> to {item}",
    "victory.goalAcorn": "<b>{count} treat</b> to {item}",
    "victory.souvenir": "{area} big furniture",
    "victory.gotLabel": "Picked",
    "victory.tapContinue": "Tap to continue",
    "victory.3.0": "A perfect day!",
    "victory.3.1": "Clever Max!",
    "victory.3.2": "Every step counted!",
    "victory.3.3": "What a lovely walk!",
    "victory.2.0": "Almost perfect. Good job!",
    "victory.2.1": "Just made it!",
    "victory.2.2": "A tail-wagging day!",
    "victory.1.2": "No rush. The balls can wait!",
    "victory.moon": "Moonlight walk complete!",
    "victory.moonFirst": "Moonlight walk!",
    "victory.moonRepeat": "Another moonlight walk",
    "victory.fireflies": " · Fireflies ×{count}",
    "victory.pickup": "Found {place}",
    "victory.pickupAgain": "Found more {place}",
    "victory.place.grass": "in the grass",
    "victory.place.bush": "under the bushes",
    "victory.place.fence": "by the fence",
    "victory.place.path": "by the path",
    "victory.place.soap": "by the suds",
    "victory.place.pit": "by the hole",
    "victory.place.paint": "by the paint",
    "victory.place.water": "by the water",
    "victory.place.hill": "below the hill",
    "victory.plus": "+{count}",
    "victory.acorns": "{count} treats",
    "victory.acorn": "{count} treat",
    "victory.double": "Double reward",
    "victory.doubled": "Double the treats!",
    "victory.adIncomplete": "Finish the ad to double your reward.",
    "victory.treasureAllSock": "Three treasures and a sock!",
    "victory.treasureAll": "Found every treasure!",
    "victory.treasureSock": "A sneaky sock… Treasures: {count}!",
    "victory.treasureSome": "Treasures: {count}! Sniff again tomorrow.",
    "victory.steps": "Moves",
    "victory.treasures": "Treasures",
    "victory.par": "Par",
    "victory.treasureWalk": "Treasure walk",
    "victory.dailyDone": "One errand done!",
    "victory.lunchDone": "Today's neighborhood walk complete!",
    "victory.daily": "Errand",
    "victory.lunch": "Neighborhood walk · {day}",
    "victory.areaDone": "Yard complete!",
    "victory.chapterArt": "Chapter art unlocked",
    "victory.chipLabel": "Pieces",
    "victory.acornLabel": "Treats",
    "victory.day.0": "Monday",
    "victory.day.1": "Tuesday",
    "victory.day.2": "Wednesday",
    "victory.day.3": "Thursday",
    "victory.day.4": "Friday",
    "victory.day.5": "Saturday",
    "victory.day.6": "Sunday",
    "growth.1.step.1": "Tent Bed",
    "growth.1.step.2": "House Frame",
    "growth.1.step.3": "Max’s House",
    "growth.1.step.4": "Shade canopy",
    "growth.1.step.5": "Wooden deck",
    "growth.1.step.6": "Woodpile and lamp",
    "growth.1.name": "Max’s House",
    "growth.1.buildTitle": "Build Max’s House",
    "growth.2.step.1": "Tile Floor & Tub",
    "growth.2.step.2": "Trestle Frame",
    "growth.2.step.3": "Water Tower",
    "growth.2.step.4": "Bubbles & Soap",
    "growth.2.step.5": "Step & Towel Rack",
    "growth.2.step.6": "Brass Tap & Lantern",
    "growth.2.name": "Water Tower",
    "growth.2.buildTitle": "Build the Water Tower",
    "growth.3.step.1": "Dry Hollow",
    "growth.3.step.2": "Water & Plank",
    "growth.3.step.3": "Duck House",
    "growth.3.step.4": "First Duck",
    "growth.3.step.5": "White Stones & Lilies",
    "growth.3.step.6": "Two Ducks & Lantern",
    "growth.3.name": "Duck House",
    "growth.3.buildTitle": "Build the Duck House",
    "growth.4.step.1": "Acorn",
    "growth.4.step.2": "Oak Sprout",
    "growth.4.step.3": "Treehouse",
    "growth.4.step.4": "Little Birdhouse",
    "growth.4.step.5": "Whitewash & Stones",
    "growth.4.step.6": "Autumn Leaves & Lights",
    "growth.4.name": "Oak Tree",
    "growth.4.buildTitle": "Grow an Oak Tree",
    "growth.5.step.1": "Round Frame",
    "growth.5.step.2": "Jumping Mat",
    "growth.5.step.3": "Jump Platform",
    "growth.5.step.4": "Paw Print",
    "growth.5.step.5": "Colorful Springs",
    "growth.5.step.6": "Brass Handrail",
    "growth.5.name": "Jump Platform",
    "growth.5.buildTitle": "Build the Jump Platform",
    "growth.6.step.1": "Stone Base & Film",
    "growth.6.step.2": "Tunnel Frame",
    "growth.6.step.3": "Polytunnel",
    "growth.6.step.4": "Harvest Basket",
    "growth.6.step.5": "White Beds & Signs",
    "growth.6.step.6": "Brass Watering Can",
    "growth.6.name": "Polytunnel",
    "growth.6.buildTitle": "Build the Polytunnel",
    "growth.7.step.1": "Stone Base & Planks",
    "growth.7.step.2": "Shed Frame",
    "growth.7.step.3": "Delivery Shed",
    "growth.7.step.4": "Delivery Sign",
    "growth.7.step.5": "White Mailbox",
    "growth.7.step.6": "Hay & Tools",
    "growth.7.name": "Delivery Shed",
    "growth.7.buildTitle": "Build the Delivery Shed",
    "growth.8.step.1": "Workbench",
    "growth.8.step.2": "Paint Set",
    "growth.8.step.3": "Paint Shed",
    "growth.8.step.4": "Colorful Fence",
    "growth.8.step.5": "Swatches & Flowers",
    "growth.8.step.6": "Rainbow Awning & Light",
    "growth.8.name": "Paint Shed",
    "growth.8.buildTitle": "Build the Paint Shed",
    "growth.9.step.1": "Cat Pawprints",
    "growth.9.step.2": "Peeking over the Wall",
    "growth.9.step.3": "Cat Cafe",
    "growth.9.step.4": "Water Bowl and Bell",
    "growth.9.step.5": "Name Tags and Sign",
    "growth.9.step.6": "Dark Wood Feeding Table",
    "growth.9.name": "Cat Cafe",
    "growth.9.buildTitle": "Build the Cat Cafe",
    "growth.10.step.1": "Post",
    "growth.10.step.2": "Pinwheel Blades",
    "growth.10.step.3": "Windmill",
    "growth.10.step.4": "Wind Ribbons",
    "growth.10.step.5": "Little Pinwheels",
    "growth.10.step.6": "Brass Blades & Light",
    "growth.10.name": "Windmill",
    "growth.10.buildTitle": "Build the Windmill",
    "growth.starTitle": "{area} · Treats",
    "growth.mystery": "A surprise awaits",
    "growth.unlockStage": "Clear stage {stage} to reveal it",
    "growth.goal.first": "First parcel:",
    "growth.goal.next": "Next parcel:",
    "growth.goal.deluxe": "Final upgrade:",
    "victory.giftRecipe": "<b>{name}</b> blueprint",
    "victory.giftBundle": "{mat} ×{n} · {paw} treats",
    "victory.giftAcorn": "{paw} treats",
    "victory.clearAuto": "Walk finished",
    "part.base": "Base",
    "part.body": "Body",
    "part.top": "Finish",
    "growth.partN": "Part {n} / 3",
    "growth.partWait": "Later",
    "growth.make": "Make it",
    "growth.makeN": "Build the {part}",
    "growth.needLabel": "Needs",
    "growth.bom": "PARTS",
    "growth.bomUsed": "USED",
    "growth.pourSub": "Add {put} · {rest} more to go",
    "growth.pourAll": "Add",
    "growth.build": "Build",
    "growth.stampDone": "DONE",
    "growth.nextTitle": "Next blueprint",
    "growth.lack": "{n} short",
    "growth.from2": "{mat} is found in {places}",
    "growth.buildStep": "Build: {label}",
    "growth.buildNow": "Build",
    "growth.putN": "Add {n} {mat}",
    "growth.putSome": "Add the {n} you have",
    "growth.putNone": "No {mat}",
    "growth.short": "{n} more {mat} needed · from {places}",
    "growth.lastPart": "Adding this finishes {label}",
    "growth.builtToast": "{label} done · {n}/{tot}",
    "growth.planTag": "Blueprint",
    "growth.allBuilt": "All built",
    "growth.nextAt": "Next blueprint comes with the stage {stage} parcel",
    "growth.short": "{n} more {mat} needed",
    "growth.from": "Found in {places}",
    "growth.pieces": "{got}/{total}",
    "growth.piecesOf": "{name} {got}/{total}",
    "growth.stageUnit": " stages",
    "growth.stageUnit.one": " stage",
    "tool.noTarget": "Nothing to use it on here",
    "hint.unlocked": "Grandpa's Training Added!",
    "common.tapContinue": "Tap to continue",
    "game.noMoves": "Out of moves",
    "game.exitQuestion": "Leave this walk?",
    "game.keepTrying": "Keep Trying",
    "game.skipAd": "Watch an ad to skip",
    "game.skipLimit": "Once per area",
    "menu.bag": "Bag",
    "common.nice": "Lovely!",
    "menu.decorations": "Decorations",
    "menu.decorate": "🔨 Decorate",
    "yard.plantQuestion": "What shall we plant?",
    "yard.paintQuestion": "What shall we paint?",
    "yard.paintApply": "Paint",
    "yard.paintCurrent": "In use",
    "yardShort.playDays": "Play {count} more days",
    "yardShort.sameCrop": "{max} of one crop",
    "yard.harvested": "Harvested <b>{count} {name}</b>!",
    "yardShort.mealWait": "{time}",
    "yardShort.growWait": "Grows in {time}",
    "yardShort.parcelWait": "Gift in {time}",
    "common.walk": "Go for a Walk",
    "common.free": "Free",
    "common.skip": "Skip",
    "common.cancel": "Cancel",
    "common.unlockAfter": "Clear {stage} to unlock",
    "hint.sniff.name": "Stomp!",
    "hint.dest.name": "Jump!",
    "hint.order.name": "Fetch!",
    "hint.sniff.short": "Stomp",
    "hint.dest.short": "Jump",
    "hint.order.short": "Fetch",
    "hint.sniff.description": "Stomps the <b>bush</b> beside Max into a path",
    "hint.dest.description": "Jumps the <b>ball</b> beside Max onto the ground past it",
    "hint.order.description": "Fetches the <b>ball</b> to the tile beside Max",
    "hint.sniff.how": "Fences can't be stomped",
    "hint.dest.how": "The ball stays put",
    "hint.order.how": "Never straight onto a mat",
    "hint.sniff.coach": "Pick a bush to stomp",
    "hint.dest.coach": "Pick where to land",
    "hint.order.coach": "Pick a ball, then where it goes",
    "story.intro1": "<b>Max lives on<br>Grandpa’s farm.</b>",
    "story.intro2": "<b>Max loves playing with his toys<br>and Grandpa.</b>",
    "story.intro1.alt": "Max at Grandpa’s farm",
    "story.intro2.alt": "Max nudges his chicken toy onto its mat while Grandpa watches",
    "callout.cartH.name": "Horizontal Cart",
    "callout.cartH.text": "Push left or right only",
    "map.leftMat": "{n} walks with treats left",
    "map.leftGo": "Go",
    "map.districtLocked": "Finish this neighborhood to open the next",
    "map.woof": "Woof!",
    "guide.base.name": "Let’s Walk",
    "guide.base.text": "Push the ball <b>onto the cushion</b>",
    "guide.ice.name": "Soapy Ground",
    "guide.ice.text": "Balls <b>slide to the end</b> of the soap",
    "guide.slope.name": "Slope",
    "guide.slope.text": "Balls <b>roll along the arrow</b>",
    "guide.slopeback.name": "Reverse Slope",
    "guide.slopeback.text": "Even when pushed backward,|balls <b>roll along the arrow</b>",
    "guide.billiard.name": "Bump!",
    "guide.billiard.text": "A rolling ball <b>pushes the ball ahead</b>",
    "guide.slopebilliard.name": "Slope Bump",
    "guide.slopebilliard.text": "A ball rolling downhill <b>pushes other balls</b>",
    "guide.trampknock.name": "Bounce Bump",
    "guide.trampknock.text": "The ball on the landing tile|gets <b>pushed one tile</b>",
    "guide.trampback.name": "Short Landing",
    "guide.trampback.text": "Blocked? Land on the <b>nearer tile</b>|Both blocked? Stay <b>on the trampoline</b>",
    "guide.pit.name": "Hole",
    "guide.pit.text": "A ball fills the hole|and <b>makes a path</b>",
    "guide.bone.name": "Bone",
    "guide.bone.text": "Pick up the bone and <b>bury it in a hole</b>|The buried spot stays blocked",
    "guide.furrow.name": "Narrow Furrow",
    "guide.furrow.text": "<b>Only Max</b> can pass through",
    "guide.dpit.name": "Hole",
    "guide.dpit.text": "A ball fills the hole|and <b>makes a path</b>",
    "guide.crop.name": "Plant Crops",
    "guide.crop.text": "<b>Plant a crop</b> in a hole|It becomes <b>a path</b>",
    "guide.dureong.name": "Soil Mound",
    "guide.dureong.text": "Each push moves it <b>one tile and shrinks it</b>|It disappears after <b>three pushes</b>|Push it into a hole to <b>make a path</b>",
    "guide.cart.name": "Vertical Cart",
    "guide.cart.text": "Push it <b>up or down only</b>",
    "guide.cartH.name": "Horizontal Cart",
    "guide.cartH.text": "Push it <b>left or right only</b>",
    "guide.color.name": "Match Colors",
    "guide.color.text": "Push each ball onto|a <b>matching cushion</b>",
    "guide.paint.name": "Paint",
    "guide.paint.text": "Balls <b>change to the paint’s color</b>|Match them to the same-color cushion",
    "guide.log.name": "Parcel Box",
    "guide.log.text": "Boxes move <b>one tile per push</b>",
    "guide.logpit.name": "Box Bridge",
    "guide.logpit.text": "Push a box into a hole|to <b>make a path</b>",
    "guide.valve.name": "Garden Hose",
    "guide.valve.text": "Press the valve to <b>stop the water</b>",
    "guide.logvalve.name": "Box and Hose",
    "guide.logvalve.text": "A box on the valve|<b>keeps the water off</b>",
    "guide.flow.name": "Current",
    "guide.flow.text": "Balls follow the current|Max can’t enter the water|Push a banked ball <b>back against the current</b>",
    "guide.pool.name": "Pool",
    "guide.pool.text": "Balls get <b>stuck in the pool</b>|<b>Bump with another ball</b> to free them",
    "guide.bridge.name": "Bridge",
    "guide.bridge.text": "Balls on land go <b>over</b> the bridge|Floating balls go <b>under</b> it",
    "guide.bridge.over": "A land ball crosses <b>over the deck</b>|and never stops there — it rolls on and <b>knocks</b>",
    "guide.bridge.under": "A ball in the current passes <b>under the bridge</b>",
    "guide.catbox.name": "Yulmu",
    "guide.catbox.text": "When a ball touches Yulmu,|Yulmu hides in the <b>next empty box</b>|You can’t pass through Yulmu’s spot",
    "guide.greedy.name": "Susu",
    "guide.greedy.text": "Susu moves: cushion → ball → bin|<b>You can’t use Susu’s spot</b>|<b>Only Max</b> can pass through a bin",
    "guide.twocats.name": "Yulmu and Susu",
    "guide.twocats.text": "Yulmu moves to a <b>box</b>|Susu moves to a <b>bin</b>",
    "guide.wind.name": "Pinwheel",
    "guide.wind.text": "One full turn blows balls|<b>one tile toward the flag</b>",
    "guide.windbox.name": "Wind Shelter",
    "guide.windbox.text": "Boxes and balls on cushions|<b>stay put in the wind</b>",
    "guide.windpush.name": "Ride the Wind",
    "guide.windpush.text": "Push on a windy turn|to move <b>one extra tile</b>",
    "guide.napcat.name": "Watching Cat",
    "guide.napcat.text": "Leave the flowerbed’s side,|and the cat takes your spot|A ball pushes it <b>back to the flowerbed</b>",
    "guide.catwalk.name": "Walking Cat",
    "guide.catwalk.text": "The cat moves <b>one tile with each step</b>|It turns around when blocked",
    "guide.tramp.name": "Trampoline",
    "guide.tramp.text": "Balls <b>jump over one tile</b>",
    'app.title': 'Walk with Max',
    'app.subtitle': 'A Cozy Walk Puzzle',
    'common.next': 'Next',
    'common.ok': 'Got it',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.start': 'Start',
    'common.lookAround': 'Look Around',
    'common.later': 'Later',
    'common.continue': 'Keep Walking',
    'common.exit': 'Exit',
    'common.retry': 'Restart',
    'common.undo': 'Undo',
    'settings.title': 'Settings',
    'settings.sound': 'Sound Effects',
    'settings.music': 'Music',
    'settings.vibration': 'Vibration',
    'settings.directionButtons': 'Direction Buttons',
    'settings.buttonSide': 'Button Side',
    'settings.left': 'Left',
    'settings.right': 'Right',
    'settings.reset': 'Reset Progress',
    'settings.privacy': 'Privacy Policy',
    'settings.language': 'Language',
    'accessibility.help': 'Help',
    'accessibility.settings': 'Settings',
    'accessibility.exit': 'Exit',
    'accessibility.close': 'Close',
    'accessibility.back': 'Back',
    'accessibility.up': 'Up',
    'accessibility.down': 'Down',
    'accessibility.left': 'Left',
    'accessibility.right': 'Right',
    'rotate.title': 'Turn your phone upright',
    'rotate.body': "Max's walk fits best in portrait mode",
    'district.1.name': "Max's Yard",
    'district.2.name': 'Bubbly Backyard',
    'district.3.name': 'Babbling Brook',
    'district.4.name': 'Acorn Hill',
    'district.5.name': 'Bouncy Playground',
    'district.6.name': 'Growing Garden',
    'district.7.name': 'Rattly Barn',
    'district.8.name': 'Rainbow Fence Lane',
    'district.9.name': 'Kitty Alley',
    'district.10.name': 'Pinwheel Field',
    'district.11.name': 'Festival Yard',
    'district.12.name': 'Pine Trail',
    'district.13.name': 'Delivery Road',
    'district.14.name': 'Moonlit Road',
    'district.15.name': 'Summer Days',
    'chapter.unknown': 'Walk',
    'chapter.1.name': 'Push',
    "chapter.6.name": "Two Balls",
    'chapter.11.name': 'Two Balls',
    'chapter.16.name': 'Two-Ball Practice',
    'chapter.21.name': 'Three Balls',
    'chapter.26.name': 'Push Review',
    'chapter.31.name': 'Soapy Ground',
    'chapter.36.name': 'Soap Practice',
    'chapter.41.name': 'Bump!',
    'chapter.46.name': 'Bump Practice',
    'chapter.51.name': 'Three Soapy Balls',
    'chapter.56.name': 'Backyard Review',
    'chapter.61.name': 'Current',
    'chapter.66.name': 'Riverbank',
    'chapter.71.name': 'Pool',
    'chapter.76.name': 'Pool Practice',
    'chapter.81.name': 'Bridge',
    'chapter.86.name': 'Brook Review',
    'chapter.91.name': 'Slope',
    'chapter.96.name': 'Slope Practice',
    'chapter.101.name': 'Slope Bump',
    'chapter.106.name': 'Slope Bump Practice',
    'chapter.111.name': 'Three Balls on Slopes',
    'chapter.116.name': 'Hill Review',
    'chapter.121.name': 'Trampoline',
    'chapter.126.name': 'Bounce Bump',
    'chapter.131.name': 'Bounce Bump Practice',
    'chapter.136.name': 'Bounce Back',
    'chapter.141.name': 'Bounce Back Practice',
    'chapter.146.name': 'Trampoline Review',
    'chapter.151.name': 'Hole',
    'chapter.156.name': 'Plant Crops',
    'chapter.161.name': 'Crop Practice',
    'chapter.166.name': 'Soil Mound',
    'chapter.171.name': 'Soil and Crops',
    'chapter.176.name': 'Garden Review',
    'chapter.181.name': 'Parcel Box',
    'chapter.186.name': 'Two Boxes',
    'chapter.191.name': 'Vertical Cart',
    'chapter.196.name': 'Two-Way Carts',
    'chapter.201.name': 'Boxes and Carts',
    'chapter.206.name': 'Barn Review',
    'chapter.211.name': 'Paint',
    'chapter.216.name': 'Paint Practice',
    'chapter.221.name': 'Garden Hose',
    'chapter.226.name': 'Hose Practice',
    'chapter.231.name': 'Painted Parcels',
    'chapter.236.name': 'Fence Lane Review',
    'chapter.241.name': 'Hiding Cat',
    'chapter.246.name': 'Three Boxes',
    'chapter.251.name': 'Greedy Cat',
    'chapter.256.name': 'Greedy Cat Practice',
    'chapter.261.name': 'Two Cats',
    'chapter.266.name': 'Alley Review',
    'chapter.271.name': 'Wind',
    'chapter.276.name': 'Flag Lane',
    'chapter.281.name': 'Block the Wind',
    'chapter.286.name': 'Count the Steps',
    'chapter.291.name': 'Ride the Wind',
    'chapter.296.name': 'Field Review',
    'chapter.301.name': 'Festival Paint',
    'chapter.306.name': 'Festival Slopes',
    'chapter.311.name': 'Festival Water',
    'chapter.316.name': 'Festival Finale',
    'chapter.321.name': 'Pine Grove Holes',
    'chapter.326.name': 'Pine Grove Soap',
    'chapter.331.name': 'Pine Grove Bones',
    'chapter.336.name': 'Pine Grove Slopes',
    'chapter.341.name': 'Delivery Push',
    'chapter.346.name': 'Delivery Patrol',
    'chapter.351.name': 'Delivery Bounce',
    'chapter.356.name': 'Delivery Soap',
    'chapter.361.name': 'Moonlit Bounce',
    'chapter.366.name': 'Moonlit Paint',
    'chapter.371.name': 'Moonlit Slopes',
    'chapter.376.name': 'Homeward',
    'chapter.381.name': 'Summer Soap',
    'chapter.391.name': 'Summer Slopes',
    'chapter.401.name': 'Summer Paint',
    'chapter.411.name': 'Summer Parcels',
    'chapter.421.name': 'Summer Bounce',
    'story.artLabel': '{area} scenery',
    'story.district.1': 'Grandpa opens the farm gate.\nMax races into the yard.',
    'story.district.2': "It's farm-cleaning day.\nMax dives straight into the bubbles.",
    'story.district.3': 'Clear water runs beneath the stone bridge.\nThe walking path continues across it.',
    'story.district.4': 'Grandpa often walked this hill.\nToday, Max leads the way.',
    'story.district.5': 'Grandpa turned the clearing into a playground.\nMax is the first guest.',
    'story.district.6': "It's time to plant Grandpa's garden.\nMax joins the first harvest season.",
    'story.district.7': 'The old rattly barn is finally open.\nBoxes are waiting inside.',
    'story.district.8': 'Fresh paint colors the lane.\nEven the gray balls get a new look.',
    'story.district.9': 'Cats have moved into the alley behind the farm.\nTheir ears perk up at a new visitor.',
    'story.district.10': 'A faraway breeze reaches the field.\nMax follows it to the end of the trail.',
    'language.ko': '한국어',
    'language.en': 'English',
"nav.shop": "Shop",
"nav.walk": "Walk",
"nav.yard": "Town",
"notice.dailyLocked": "The routine board opens after 50 walks (you're at {count})",
"notice.dailyDone": "That's all for today. See you tomorrow!",
"notice.dailySoon": "Neighborhood Walk is coming soon.",
"notice.adDaily": "Finish the ad to unlock another try.",
"notice.noDaily": "No more walks today.",
"notice.devAd": "<b>[{slot}]</b> Test ad — reward granted for development.",
"ad.clear2x": "Double rewards",
"ad.hint": "One command",
"ad.skip": "Skip level",
"ad.daily": "Extra daily try",
"ad.meal": "One meal",
    "billing.verify": "We couldn't verify the purchase.",
    "billing.pending": "Your treats will arrive once payment is complete.",
    "billing.unavailable": "Treat purchases are available in the released app.",
    "billing.failed": "Purchase failed. Please try again.",
    "billing.duplicate": "This purchase has already been delivered.",
    "billing.received": "{count} treats added!",
    "billing.arrived": "Your treats are here!",
    "billing.balanceChange": "Your treats {before} → {after}",
    "billing.collect": "Collect",
    "billing.thanks": "Thank you!",
    "billing.adfree": "Enjoy ad-free walks.",
    "shop.hints": "Grandpa's Training",
    "shop.feed": "Food",
    "shop.acorns": "Treats",
    "shop.stock": "In your bag · {count}",
    "shop.singleHint": "{name} · 1 hint",
    "shop.none": "None",
    "shop.half": "Half Bag",
    "shop.full": "Full Bag",
    "shop.meals": "{count} meals",
    "shop.buy": "Buy <b>{name}</b>?",
    "shop.hintN": "{name} ×{count}",
    "shop.cards": "×{count}",
    "shop.inbag": "{count} in bag",
    "shop.confirm": "Buy",
    "shop.back": "Go back",
    "shop.refill": "Get Treats",
    "shop.from": "Choose the amount you need",
    "shop.viewPacks": "View 3 packs",
    "shop.hidePacks": "Collapse",
    "shop.popular": "Popular",
    "shop.quantity": "{count} treats",
    "shop.paw1": "Treat Jar",
    "shop.paw2": "Treat Tub",
    "shop.paw3": "Treat Box",
    "shop.permanent": "For Max",
    "shop.once": "Yours to keep. No subscription.",
    "shop.owned": "Owned",
    "shop.have": "Owned",
    "shop.gift": "Claim Gift",
    "shop.group.fur": "Coat Color",
    "shop.group.wear": "Accessories",
    "shop.group.mat": "Cushion Patterns",
    "shop.layer": "Wear a hat and a neck accessory together",
    "shop.fur_white": "White",
    "shop.fur_yellow": "Golden",
    "shop.fur_black": "Black",
    "shop.fur_tri": "Tricolor",
    "shop.neck_scarf": "Red Scarf",
    "shop.neck_bell": "Collar Bell",
    "shop.head_hat": "Straw Hat",
    "shop.neck_gold": "Golden Collar",
    "shop.mat_plain": "Plain",
    "shop.mat_dot": "Polka Dots",
    "shop.mat_check": "Checks",
    "shop.mat_star": "Stars",
    "shop.goldLock": "Fully bloom 3 chapters",
    "shop.cheer": "Cheer for Max",
    "shop.cheerSub": "Ad-free + exclusive collar",
    "shop.yard": "Neighborhood Decor",
    "shop.yardSub": "Goes to your storage. In Town, tap a dashed spot to place it.",
    "shop.claim": "Get",
    "shop.zoneLock": "Clear {name} first",
    "shop.wardrobe": "Wardrobe",
    "shop.play": "Play",
    "shop.season": "Seasonal",
    "meal.empty": "The bowl is empty.<br><b>Time for a refill?</b>",
    "meal.remaining": "{count} meals left.<br><b>Top up the bowl?</b>",
    "meal.next": "Next meal in {time}",
    "meal.adLeft": "{count} left today",
    "meal.adDone": "All used for today",
    "meal.first": "Your first bag is on us",
    "meal.half": "Half Bag of Food",
    "meal.full": "Full Bag of Food",
    "meal.ad": "Watch an ad for a meal",
    "meal.adLimit": "Up to 3 per day",
    "meal.wait": "You can also wait for a refill",
    "meal.addHalf": "Half a bag added!",
    "meal.addFull": "Food added!",
    "meal.filled": "Food added — a full bowl!",
    "meal.bought": "Food bought and added!",
    "meal.one": "One meal added!",
    "notice.short": "You need {count} more treats.",
    "notice.hintShort": "You need {count} more treats.<br>Pick them up on your walks.",
    "notice.undoLimit": "No more undos for this attempt.",
    "notice.restartLimit": "No more restarts for this attempt.<br>Leave and return to try again.",
    "notice.walkOn": "Walk on",
    "notice.retry": "Walk again",
    "notice.more": "{count} more moves",
    "notice.addMoves": "{count} extra moves added!",
    "notice.next": "Next Level",
    "notice.quitMeal": "This attempt will be lost.<br>Returning will cost one meal.",
    "notice.quit": "This attempt will be lost.",
    "notice.notReady": "This walk isn't ready yet.",
    "notice.noHints": "No hints left. Get more at the Treat Shop.",
    "notice.bagAdded": "Commands added!",
    "notice.hintActive": "Refilled and activated!",
    "notice.pickBall": "Tap a <b>ball</b> first.",
    "notice.full": "The bowl is full!",
    "notice.adMeal": "Finish the ad to receive a meal.",
    "notice.adSkip": "Finish the ad to skip this level.",
    "notice.shopLocked": "Clear 2-10 to open the Treat Shop.",
    "notice.shopPlaying": "Visit the shop after your walk.<br>You have {count} treats.",
    "notice.yardLocked": "Clear 30 levels to open the yard ({count} so far).",
    "notice.yardSoon": "The yard is still being built.",
    "hud.stepsLeft": "moves left",
    "map.hardWalk": "Rough path",
    "lvcard.title": "Walk {lv}",
    "lvcard.titleFirst": "First walk",
    "lvcard.rowMat": "Snacks",
    "lvcard.grpReward": "Rewards",
    "lvcard.rowBase": "Clear",
    "lvcard.rowHint": "Training",
    "victory.giftTap": "Tap to open",
    "victory.giftPaw": "{count} treats",
    "notice.par": "You passed the shortest route.<br>That is fine — you have moves to spare.",
    "notice.lamp": "When it gets dark, <b>tap</b> to turn on the flashlight.",
    "time.hours": "{count}h",
    "time.minutes": "{count}m",
    "time.reset": "Resets at midnight · {time}",
    "note.caseFrom": "Picked up on walk {n}",
    "note.caseUnknown": "Not found yet",
    "note.caseMake": "Make the {item}",
    "note.caseDone": "{item} done!",
    "note.bpMake": "Make the blueprint",
    "note.bpLack": "{n} more pieces needed",
    "note.bpFrom": "A blueprint every 10 levels cleared in this neighborhood",
    "note.bpDone": "You have the {item} blueprint!",
    "note.bpNew": "{n} new pieces",
    "note.casePut": "Place it in {name}",
    "note.caseStanding": "Standing in {name}",
    "note.caseYardLocked": "Finish {name} to place it",
    "victory.bpPick": "{item} — a toy Max fetched",
    "victory.bpSub": "Make it on the notebook Shelf",
    "chore.c1a": "Sweep the Yard",
    "chore.c1b": "Fill the Bowl",
    "chore.c1c": "Wipe the Window",
    "chore.c2a": "Hang the Towel",
    "chore.c2b": "Change the Water",
    "chore.c2c": "Bubble Bath",
    "chore.c3a": "Skim the Leaves",
    "chore.c3b": "Stack Stones",
    "chore.c3c": "Spin the Wheel",
    "chore.c4a": "Gather Acorns",
    "chore.c4b": "Feed the Birds",
    "chore.c4c": "Light the Lantern",
    "chore.c5a": "Bounce Time",
    "chore.c5b": "Dust It Off",
    "chore.c5c": "Tighten the Springs",
    "chore.c6a": "Water the Beds",
    "chore.c6b": "Harvest",
    "chore.c6c": "Pull the Weeds",
    "chore.c7a": "Carry the Boxes",
    "chore.c7b": "Turn the Sign",
    "chore.c7c": "Empty the Mailbox",
    "chore.c8a": "Wash the Brushes",
    "chore.c8b": "Repaint the Fence",
    "chore.c8c": "Match the Swatches",
    "chore.c9a": "Set Out Food",
    "chore.c9b": "Fresh Water",
    "chore.c9c": "Polish the Tag",
    "chore.c10a": "Wipe the Blades",
    "chore.c10b": "New Ribbon",
    "chore.c10c": "Light the Lamp",
    "chore.cond.walk": "Walk {n} today",
    "chore.cond.star3": "{n} walks with three treats kept",
    "chore.cond.par": "{n} walk within par",
    "chore.cond.new": "{n} new walk",
    "chore.every3": "every three days",
    "chore.verb.house": "Feed",
    "chore.verb.colTub": "Bath",
    "chore.verb.colBrook": "Scoop leaves",
    "chore.verb.colOak": "Gather acorns",
    "chore.verb.colTramp": "Throw ball",
    "chore.verb.colDig": "Tend garden",
    "chore.verb.colBox": "Send parcel",
    "chore.verb.colPaint": "Portrait",
    "chore.verb.colCatBed": "Visit cats",
    "chore.verb.colPin": "Free the blades",
    "chore.today": "Today's Chores",
    "chore.didToday": "Done for today",
    "chore.noneToday": "The yard is quiet today",
    "chore.claim": "claim",
    "chore.none": "Build the house and chores appear",
    "chore.noneWeek": "No weekly chores yet",
    "set.fetch": "Toys",
    "set.fetchFrame": "Max's Toys",
    "set.frameHung": "A frame is on the wall",
    "set.fetchStory": "One from every neighborhood. None of it was Max's. All of it is now.",
    "note.new.bp": "Your <b>blueprints</b> live in the notebook!",
    "note.new.case": "The <b>Shelf</b> page is in your notebook!",
    "note.new.album": "An <b>Album</b> page is in your notebook!",
    "note.new.chores": "The <b>Routine</b> page is in your notebook!",
    "note.new.cal": "The <b>Calendar</b> page is in your notebook!",
    "note.build": "Blueprints",
    "note.case": "Shelf",
    "note.album": "Album",
    "note.albumEmpty": "Finish a neighborhood and its picture will appear here",
    "note.albumDone": "A walk together",
    "note.chores": "Routine",
    "chore.go": "Go",
    "chore.rwToday": "{mat} today",
    "chore.rwLater": "{mat} in {n}d",
    "chore.rwDropped": "{mat} waiting",
    "chore.rwMeal": "{n} meal(s)",
    "chore.rwCrop": "{n} {name}",
    "chore.rwCare": "Visit +1",
    "note.bp": "Blueprints",
    "note.bpGo": "Make it in Blueprints",
    "note.bpSecCol": "Small furniture blueprints",
    "note.bpSecPlan": "Big furniture blueprints",
    "note.bpBuilt": "Built in the yard",
    "note.infoBig": "{n} / {t} steps built",
    "note.infoOwn": "Ready to place in the yard",
    "note.infoBp": "The blueprint is ready",
    "note.infoBpYard": "The blueprint is ready · once this yard opens",
    "note.infoLater": "Opens after the earlier pieces",
    "note.bpLater": "Up next",
    "note.planStep": "Step {n} · {label}",
    "note.planGo": "Go to {lv}",
    "note.caseToyFrom": "Clear a level for the first time and Max fetches a toy",
    "note.lockBp": "Opens when you get a piece or a blueprint",
    "victory.chipGot": "{item} piece +1",
    "victory.chipSub": "{n} / {t} pieces · 3 make a blueprint",
    "victory.chipReady": "All pieces in — make the blueprint in the notebook",
    "note.bigYardLater": "The blueprint is ready · once the yard opens",
    "growth.hammerHint": "Tap the hammer to build",
    "note.choresOpened": "<b>Routine</b> is open<br>Care for the yard daily to get what you are short on",
    "note.planNeed": "Collect {mats} more to build",
    "note.planYardReady": "The blueprint is ready",
    "note.yardGo": "See the spot",
    "victory.planNote": "Blueprint added to your notebook",
    "victory.planNoteSub": "Collect acorns to build it in the yard",
    "victory.noteGo": "Notebook",
    "tutorial.matFirst": "<b>Treats</b> for your blueprints",
    "tutorial.matWall": "<b>Treats</b> hang on bushes and fences too<br><b>Push</b> from the side to knock them down",
    "tutorial.tool.sniff.1": "Grandpa taught Max <b>Stomp!</b><br>Tap to give the command",
    "tutorial.tool.sniff.2": "Tap from <b>beside</b> a bush<br>to stomp it into a path",
    "tutorial.tool.dest.1": "Grandpa taught Max <b>Jump!</b><br>Tap to give the command",
    "tutorial.tool.dest.2": "Tap <b>where to land</b><br>and Max jumps the ball to get there",
    "tutorial.tool.order.1": "Grandpa taught Max <b>Fetch!</b><br>Tap to give the command",
    "tutorial.tool.order.2": "Tap from <b>beside</b> a ball<br>to fetch it <b>next to Max</b>",
    "tutorial.matWallHit": "A treat fell down!",
    "tutorial.stepLimit": "Reach the cushion before you run out of steps.",
    "tutorial.acornFirst": "Treats lie along the path.<br>Step on one to pick it up.",
    "tutorial.acornUse": "You can spend treats at the shop.",
    "tutorial.acornAgain": "{n} treats left behind.<br>Walk again to pick them up.",
    "note.tipMat": "{mat} · found in {from}",
    "mat.acorn": "Treat",
    "tutorial.matCoachBush": "A <b>treat</b> hangs on this bush<br><b>Push</b> it from the side",
    "tutorial.matCoachEdge": "Treats hang on fences too<br><b>Push</b> this one",
    "tutorial.mealFirst": "<b>Routine</b> is open<br>First task: <b>feed Max</b> — he is hungry",
    "tutorial.mealChores": "Feeding comes back <b>three times a day</b><br>It is listed in your notebook <b>Routine</b>",
    "map.giftTitle": "Walk {lv} bundle",
    "map.giftLeft": "{n} parcel(s) to open",
    "map.giftOpen": "Open",
    "map.giftCoach": "Tap it to open.",
    "map.giftAtLv": "Opens on walk {lv}",
    "map.giftGot": "Received",
    "map.giftAria": "See what is in the walk {lv} bundle",
    "victory.chipMade": "{item} blueprint complete!",
    "note.bpAuto": "Three pieces turn into a blueprint on their own",
    "victory.chipMadeSub": "Build it on an empty yard spot",
    "note.srcAll": "<b>Big furniture</b> a blueprint from each hard level's first clear · <b>Small furniture</b> a blueprint every 10 levels cleared in that neighborhood",
    "note.lockYard": "Opens when Max's house is finished",
    "note.smallAt": "{n} / {t} levels · blueprint at {goal}",
    "growth.shortFrom": "{n} more {mat} needed · from {places} levels",
    "growth.shortFree": "Yard chores give three treats every 3 days",
    "growth.needMore": "{n} more {mat}",
    "growth.goBtn": "Go",
    "growth.buyMat": "Buy {n} {mat}",
    "note.bpNone": "No blueprints in progress yet",
    "note.bpDoneRow": "Blueprint done · build it on an empty yard spot",
    "note.bpBuildYard": "Build in yard",
    "note.bpYardLater": "Build once the {name} yard opens",
    "note.bpNoSlot": "No empty spot — more open as you keep visiting",
    "note.planDone": "All built",
    "note.planReady": "Ready to build",
    "note.noteAt": "Next blueprint · walk {lv} parcel",
    "note.planBuild": "Build",
    "note.planDraw": "Draw",
    "note.lockAt": "Opens after walk {n}",
    "note.lockCase": "Opens when Max fetches a toy",
    "note.lockAlbum": "Opens when you finish a neighborhood",
    "note.lockBuild": "Opens after a tough walk",
    "note.stamps": "{n} stamps",
    "diary.morning": "Morning Errands",
    "diary.evening": "Evening Routine",
    "diary.week": "This Week",
    "diary.noErrand": "Errands are on their way",
    "diary.moreSoon": "Walk the next neighborhood and errands reach further",
    "time.left": "{time} left",
    "errand.d1": "Yard",
    "errand.d2": "Backyard",
    "errand.d3": "Hill",
    "errand.d4": "Playground",
    "errand.d5": "Garden",
    "errand.d6": "Barn",
    "errand.d7": "Fence Lane",
    "errand.d8": "Alley",
    "errand.d9": "Brook",
    "errand.d10": "Field",
    "gift.title": "Today's share",
    "gift.pending": "Finish today to open Grandpa’s gift",
    "gift.ready": "All done — Max brought something back",
    "gift.got": "{what} · more tomorrow",
    "gift.kibhalf": "Half a bag of kibble",
    "settings.audioCredits": "Audio credits",
    "billing.storageUnavailable": "Your save is unavailable. Restart the app without clearing its data.",
    "billing.storageFailed": "Payment received, but saving failed. Do not buy again; restart the app to retry delivery.",
    "guide.impact": "Bump!",
    "yardTip.house": "At mealtime, fill the <b>food & water bowls</b>.<br>Mealtime comes three times a day.",
    "yardTip.colTub": "",
    "yardTip.colTramp": "Tap to toss a ball onto the trampoline.<br>Max fetches it when it bounces.",
    "yardTip.colOak": "Pick up the fallen <b>acorns</b> once a day.<br>The hill grows as you clear hard levels.",
    "yardTip.colDig": "Plant and <b>water</b> once a day.<br>Harvest when fully grown.",
    "yardTip.colBox": "Send <b>3 of the same crop</b>.<br>A thank-you gift arrives the next day.",
    "yardTip.colPaint": "Add one stroke a day to Max’s <b>portrait</b>.<br>Seven strokes finish it · then paint your yard.",
    "yardTip.colCatBed": "Tap the <b>food bowls</b> to call them<br>Susu takes the <b>roof ridge</b>; Yulmu takes the <b>awning</b>",
    "yardTip.colBrook": "Scoop the drifting <b>leaves</b> once a day.<br>A <b>stone</b> turns up every three days.",
    "yardTip.colPin": "<b>Free</b> whatever is caught on the blades.<br>The wind rolls in an <b>acorn</b>.",
    "yardCrop.carrot": "Carrot",
    "yardCrop.potato": "Potato",
    "yardCrop.radish": "Radish",
    "yardDeco.ball": "Ball basket",
    "yardDeco.hoop": "Hoop",
    "yardDeco.bunting": "Bunting",
    "yardPalette.base": "Original",
    "yardPalette.blue": "Blue",
    "yardPalette.sun": "Yellow & green",
    "yardPalette.rose": "Pink",
    "yardPalette.rain": "Rainbow",
    "yardPay.carrot": "1 Welcome Sign",
    "yardPay.potato": "1 bag of food",
    "yardPay.radish": "12 acorns",
    "yardStatus.mealDone": "All {count} meals served today",
    "yardStatus.feed": "Feed",
    "yardStatus.mealReady": "Today: {count} / {max} meals",
    "yardStatus.mealWait": "{time}",
    "yardStatus.bathDone": "Clean for today",
    "yardStatus.wash": "Wash",
    "yardStatus.bathReady": "Time for a bath",
    "yardStatus.walks": "Walks {count}/{max}",
    "yardStatus.replant": "Replant",
    "yardStatus.gather": "Gather acorns",
    "yardStatus.oakDrop": "Acorns have fallen",
    "yardStatus.oakDone": "All gathered today",
    "yardStatus.water": "Water",
    "yardStatus.oakWater": "Thirsty · growth {count} / {max}",
    "yardStatus.oakWait": "Growth {count} / {max}<br>Grows in {time}",
    "yardStatus.hop": "Hop!",
    "yardStatus.play": "Toss the ball",
    "yardStatus.playReady": "Toss a ball?",
    "yardStatus.playDone": "Played fetch today",
    "yardStatus.decoWait": "<br>Play {count} more days to get {name}",
    "yardStatus.harvest": "Harvest",
    "yardStatus.ripe": "{name} is ready to harvest",
    "yardStatus.cropWater": "{name} · growth {count} / {max}<br>Thirsty",
    "yardStatus.plant": "Plant",
    "yardStatus.pickCrop": "What shall we plant?",
    "yardStatus.cropWait": "{name} · growth {count} / {max}<br>Grows in {time}",
    "yardStatus.stroke": "Add a stroke",
    "yardStatus.portReady": "Max is posing · stroke {count} / {max}",
    "yardStatus.unstick": "Free the blades",
    "yardStatus.pinStuck": "A {name} is caught on the blades",
    "pin.stuck.kite": "kite",
    "pin.stuck.hat": "straw hat",
    "pin.stuck.sock": "sock",
    "pin.stuck.sack": "acorn sack",
    "yardStatus.pickup": "Collect",
    "yardStatus.matWait": "More {name} in {count} days",
    "yardStatus.windReady": "The breeze brought acorns",
    "yardStatus.windDone": "Today's acorns collected",
    "yardStatus.windWait": "The breeze will bring acorns",
    "yardStatus.catsHere": "Susu and Yulmu are resting · tap to stir them",
    "yardStatus.catsAway": "They ran off · back soon",
    "yardStatus.rainbow": "Gather 90 acorns in {district} for rainbow paint",
    "yardStatus.palette": "{name} unlocks at {level}",
    "yardStatus.paintDone": "All colors unlocked · repaint anytime",
    "yardStatus.collect": "Collect",
    "yardStatus.gift": "Thank-you gift",
    "yardStatus.parcelReady": "Parcel arrived · {name}",
    "yardStatus.parcelWait": "Gift arrives in {time}<br>{reward}",
    "yardStatus.send": "Send",
    "yardStatus.sendReady": "Choose a crop to send",
    "yardStatus.sendWait": "Collect {max} of the same crop",
  };
});
