(function(root, factory) {
  const value = factory();
  if (typeof window === 'undefined' && typeof module === 'object' && module.exports) module.exports = value;
  else (root.WWM_LOCALES || (root.WWM_LOCALES = {})).ko = value;
})(typeof globalThis !== 'undefined' ? globalThis : this, function() {
  return {
    "cats.noHouse": "수수가 올라갈 <b>맥스 하우스</b>가 아직 없어요",
    "cats.noParcel": "율무가 숨을 <b>택배 상자</b>가 아직 없어요",
    "cats.seated": "벌써 제자리에 앉아 있어요",
    "cats.shortBoth": "둘 다 제자리",
    "cats.shortSusu": "수수는 지붕에",
    "cats.shortYulmu": "율무는 상자에",
    "cats.shortRoaming": "둘 다 마당에",
    "cats.shortSusuRoaming": "수수는 마당에",
    "yard.future": "언젠가 만나요",
    "yard.unmet": "아직 만나지 못했어요",
    "yard.story.colCatBed": "수수와 율무가 이따금 쉬어 간다.",
    "yard.story.colBrook": "오리 둘이 물 위를 천천히 돈다.",
    "yard.indexTitle": "맥스의 마당",
    "yard.seeYardAll": "마당 둘러보기",
    "hood.stage.0": "이제 막 열렸어요",
    "hood.stage.1": "자리잡는 중",
    "hood.stage.2": "정들었어요",
    "hood.stage.3": "살아났어요",
    "hood.left": "{n}판 더 걸으면 다음",
    "hood.grew": "{name}{particle} 조금 살아났어요 — {stage}",
    "hood.slotOpened": "{name}에 놓을 자리가 하나 늘었어요",
    "hood.backToMap": "{name} — 농장 지도로",
    "hood.lockedNext": "{name} — {lv}번째 산책에서 설계도를 받아요",
    "hood.lockedFar": "{name}부터 차례로 걸어요",
    "hood.mapHint": "마당을 눌러 둘러보세요",
    "hood.mapTodo": "오늘 들를 곳 {n}곳",
    "hood.mapNext": "다음: {name}",
    "hood.grewSlot": "{name}{particle} 조금 살아났어요 — 놓을 자리가 하나 늘었어요",
    "hood.signPick": "{mat} 줍기",
    "hood.signDone": "✓ 내일 또",
    "hood.signWait": "기다리는 중",
    "hood.signNeedHouse": "맥스 하우스를 지으면 밥때가 와요",
    "hood.signNeedBowl": "밥그릇을 지으면 밥을 채워요",
    "hood.signPaint": "칠하기",
    "hood.signCats": "부르기",
    "hood.matGot": "{mat} +1 · 이제 {n}개",
    "hood.slotGoWalk": "{name} 걸으러 가기",
    "yardStatus.scoop": "낙엽 건지기",
    "yardStatus.brookReady": "물살에 낙엽이 떠내려와요",
    "yardStatus.brookDone": "오늘 낙엽은 다 건졌어요",
    "hood.slotsN": "자리 {n}",
    "hood.slotWhere": "{name} · 빈 자리",
    "hood.slotWhereTaken": "{name} · 놓인 자리",
    "hood.slotNow": "바로 놓을 수 있어요",
    "hood.slotMaking": "만드는 중",
    "hood.slotNextCol": "다음 작은 가구",
    "hood.slotPlaced": "이 자리에 놓여 있어요",
    "hood.slotTagPlaced": "놓임",
    "hood.slotTagOwn": "놓기",
    "hood.slotTagBp": "설계도",
    "hood.slotTagReady": "간식 다 있음",
    "hood.slotTagWalk": "{n}판 더",
    "hood.slotTagLater": "그다음",
    "hood.slotPut": "여기 놓기",
    "hood.slotBuild": "짓기",
    "hood.slotWalkBtn": "걸으러 가기",
    "hood.slotLater": "그다음 {n}개",
    "hood.slotLaterSub": "앞의 것을 만들면 열려요",
    "hood.slotCareLeft": "{n}번 더",
    "hood.slotTitle": "무엇을 놓을까요?",
    "hood.slotSwap": "{item}{particle} 바꾸기",
    "hood.slotEmpty": "아직 가진 장식이 없어요",
    "hood.slotShop": "상점에서 고르기",
    "hood.slotTake": "치우기",
    "hood.slotHave": "{n}개",
    "hood.slotStanding": "여기 서 있어요",
    "hood.slotReady": "놓을 수 있어요",
    "hood.slotNeedMat": "간식을 넣는 중",
    "shop.deco": "장식",
    "shop.haveN": "{n}개 있음",
    "yard.indexTodo": "오늘 할 일 {n}",
    "yard.seeYard": "둘러보기",
    "yard.howTo": "사용법 보기",
    "yard.chooseMove": "옮길 물건을 눌러요",
    "yard.brush.grass": "잔디",
    "yard.brush.road": "길",
    "yard.brush.brook": "물",
    "yard.brush.fence": "울타리",
    "yard.brush.turn": "돌리기",
    "yard.cat.bld": "건물",
    "yard.cat.floor": "바닥",
    "yard.cat.fence": "울타리",
    "yard.bldEmpty": "마당에 선 건물이 없어요",
    "yard.free": "무료",
    "yard.signHouse": "맥스네",
    "yard.signYard": "맥스네 마당",
    "yard.bathRub": "맥스를 눌러 거품을 내요",
    "yard.replanted": "도토리를 <b>다시 심었어요</b><br>물을 주면 내일 자라요",
    "yard.oakMature": "참나무가 다 자랐어요!<br>눌러서 도토리를 다시 심을 수 있어요",
    "yard.oakGrew": "참나무가 자랐어요 — <b>{stage}</b><br>{reward} · 오늘도 물을 주세요",
    "yard.oakStage1": "새싹",
    "yard.oakStage2": "어린 나무",
    "yard.oakStage3": "다 자란 참나무",
    "yard.played": "맥스가 물어 왔어요! {reward}",
    "yard.planted": "<b>{name}</b>{particle} 심었어요<br>물을 주면 내일 자라요",
    "yard.cropMature": "<b>{name}</b>{particle} 다 자랐어요!<br>눌러서 수확해 주세요",
    "yard.cropGrew": "{name}{particle} 자랐어요 — <b>{count} / {max}</b><br>오늘도 물을 주세요",
    "yard.roof": "지붕",
    "yard.rim": "테두리",
    "yard.flowers": "꽃",
    "yard.fence": "울타리",
    "yard.hedge": "산울타리",
    "yard.nothingToPaint": "아직 칠할 물건이 없어요",
    "yard.paintUnlock": "<b>{level}판</b>을 걸으면 열려요",
    "yard.sendQuestion": "무엇을 보낼까요?",
    "yard.sendTip": "보내면 {time} 뒤에 답례가 와요",
    "yard.cropMissing": "{name}{particle} <b>{count}개</b> 모자라요",
    "yard.sent": "<b>{name} {count}개</b>를 보냈어요<br><b>{time}</b> 뒤에 {reward}{particle} 와요",
    "yard.parcelReceived": "택배가 왔어요 — <b>{reward}</b>",
    "yard.plantTip": "심고 하루 한 번 물을 주면 사흘 만에 자라요",
    "yard.emptyAlbum": "아직 모은 게 없어요<br>산책하다 보면 하나씩 생겨요",
    "yard.place": "놓기",
    "yard.act": "하기",
    "yard.mealShortDone": "다 먹었어요",
    "yard.bathShortDone": "씻었어요",
    "yard.colors": "색 {count} / {max}",
    "yard.foundBone": "옛날에 묻어둔 뼈다귀 발견! ",
    "yard.foundSomething": "킁킁… 뭔가 찾았다! ",
    "yard.clearLand": "개간하기",
    "yard.landSoon": "곧 열려요",
    "yard.landTip": "덤불을 걷어내면 맥스의 땅이 넓어져요",
    "yard.story.colTeddy": "어릴 적 맥스가 귀를 물어뜯은 곰이다.",
    "yard.story.colDisc": "테두리마다 맥스의 이빨 자국이 남았다.",
    "yard.story.colSign": "할아버지가 흔들흔들, 맥스는 그 발치에서 꾸벅.",
    "yard.story.colShade": "맥스 이름이 새겨진 받침. 물은 늘 가득이다.",
    "yard.story.colShoeRack": "뼈다귀는 늘 방석 위에 두고 잔다.",
    "yard.story.colTub": "목욕 전엔 꼭 한 번 버틴다.",
    "yard.story.colDuck": "맥스가 세게 문 뒤로 삑 소리가 안 난다.",
    "yard.story.colBrush": "맥스는 빗을 때만 얌전하다.",
    "yard.story.colTramp": "맥스는 세 번째에 제일 높이 뛴다.",
    "yard.story.colOak": "언덕에서 물어 온 도토리가 그늘이 됐다.",
    "yard.story.colDig": "물 줄 때면 맥스가 옆에 와 앉는다.",
    "yard.story.colBox": "답례가 올 때면 맥스가 먼저 안다.",
    "yard.story.colPaint": "붓을 들면 맥스도 구경하러 온다.",
    "yard.story.colRbrush": "붓 끝에 일곱 색이 남아 있다.",
    "yard.story.colPin": "바람이 불면 마당이 먼저 안다.",
    "yard.story.colSled": "맥스는 타는 것보다 쫓는 걸 좋아한다.",
    "yard.story.colCone": "맥스가 딱 하나만 골라 물어 왔다.",
    "yard.story.colDipper": "맥스는 첫 바가지 물에 늘 놀란다.",
    "yard.story.colSoapBag": "거품이 나면 맥스가 코를 들이민다.",
    "yard.story.colSkip": "세 번 튀었다. 맥스는 물속을 봤다.",
    "yard.story.colLeafBoat": "띄우면 맥스가 끝까지 따라간다.",
    "yard.story.colStep": "맥스는 두 번째 돌을 늘 건너뛴다.",
    "yard.story.colCairn": "맥스가 스치면 맨 위 돌이 떨어진다.",
    "yard.story.colBall": "던지면 맥스보다 먼저 돌아온다.",
    "yard.story.colStick": "물어 오지만 놓지는 않는다.",
    "yard.story.colRope": "맥스는 줄이 도는 걸 구경만 한다.",
    "yard.story.colScare": "새는 안 쫓고 맥스만 짖는다.",
    "yard.story.colTrowel": "맥스가 판 자리에 다시 심었다.",
    "yard.story.colSeedBox": "맥스는 뚜껑 여는 소리를 안다.",
    "yard.story.colCan": "굴러가면 맥스가 끝까지 쫓는다.",
    "yard.story.colBlanket": "창고에서 맥스가 먼저 찾아낸 담요다.",
    "yard.story.colKey": "맥스는 열쇠 소리를 알아듣는다.",
    "yard.story.colPebble": "맥스가 물어 온 돌에 색을 칠했다.",
    "yard.story.colPlank": "네 색 중 맥스는 초록만 냄새 맡는다.",
    "yard.story.colMarble": "굴러가면 맥스가 코로 멈춘다.",
    "yard.story.colWand": "고양이보다 맥스가 더 좋아한다.",
    "yard.story.colLamp": "불이 켜지면 고양이가 먼저 모인다.",
    "yard.story.colChime": "소리가 나면 맥스가 귀를 세운다.",
    "yard.story.colBalloon": "줄을 놓치면 맥스가 끝까지 쫓는다.",
    "yard.story.colVane": "닭이 돌면 맥스가 따라 돈다.",
    "yard.story.colSlipper": "나머지 한 짝은 아직도 못 찾았다.",
    "yard.story.colTwig": "물에서 건져 와 마당에 말려 뒀다.",
    "yard.story.colTennis": "누구 건지 모른다. 이제 맥스 거다.",
    "yard.story.colCarrot": "뽑은 게 아니라 물어 온 거라고 우긴다.",
    "yard.story.colTape": "이빨에 붙어서 한참 떼어 냈다.",
    "yard.story.colSock": "어느 집 빨랫줄에서 왔는지는 묻지 않기로 했다.",
    "yard.story.colCatBell": "고양이는 목줄이 가벼워졌다고 좋아했다.",
    "yard.story.colSeed": "물어 오는 동안 반은 날아갔다.",
    "yard.story.colFlag": "언덕 꼭대기에서 가져온 깃발이다.",
    "yard.story.signYard": "맥스는 이 앞에서 꼭 뒤를 돌아본다.",
    "yard.story.flower": "맥스는 냄새만 맡고 지나간다.",
    "yard.story.bowl": "산책 후 제일 먼저 달려가는 곳이다.",
    "yard.story.basket": "공은 하나도 양보하지 않는다.",
    "yard.story.tree": "그늘이 딱 맥스 한 마리 크기.",
    "yard.story.bench": "맥스랑 나란히 앉기엔 넉넉하다.",
    "yard.story.house": "낮잠은 늘 마당 한가운데서 잔다.",
    "yard.story.tree2": "봄이 아니어도 꽃이 핀다.",
    "yard.story.mailbox": "택배가 오면 맥스가 먼저 안다.",
    "yard.story.pond": "헤엄은 아직 무서워 발만 담근다.",
    "yard.story.swing": "혼자 흔들리면 맥스가 짖는다.",
    "common.receive": "받기",
    "common.open": "열기",
    "full.five": "밥그릇 ×5",
    "full.ten": "밥그릇 ×10",
    "full.halfDesc": "밥그릇 5개를 채워요",
    "full.fullDesc": "밥그릇 10개를 채워요",
    "full.halfStarted": "밥그릇 5개를 채웠어요!",
    "full.started": "밥그릇 10개를 채웠어요!",
    "full.bought": "밥그릇 10개를 채웠어요!",
    "full.remaining": "배부른 시간 {time}",
    "cats.both": "수수는 지붕에 · 율무는 택배 상자에",
    "cats.susu": "수수는 지붕에 · 율무는 마당 산책 중",
    "cats.yulmu": "율무는 택배 상자에 · 수수는 마당 산책 중",
    "cats.roaming": "둘 다 마당 산책 중",
    "cats.susuRoaming": "수수가 마당 산책 중",
    "tutorial.firstDistrict": "<b>맥스네 마당</b>을 열어 볼까요?",
    "tutorial.firstGo": "<b>산책 가기</b>를 누르면<br>첫 산책이 시작돼요",
    "tutorial.otherBall": "다른 공도 하나씩 눌러 봐요",
    "stamp.acorns": "간식 {count}",
    "stamp.hint": "훈련 {count}번",
    "stamp.parcel": "택배 상자",
    "stamp.week": "일주일을 같이 걸었어요",
    "stamp.day": "산책 {day}일째",
    "stamp.dayShort": "{day}일",
    "stamp.today": "오늘",
    "stamp.progress": "{day} / {max}",
    "stamp.secret": "아직 비밀이에요",
    "stamp.opensIn": "{count}일 뒤에 열려요",
    "stamp.reward": "오늘은 <b>{item}</b>",
    "stamp.claimed": "오늘 것은 받았어요",
    "stamp.open": "열어 보기",
    "stamp.title": "할아버지의 선물",
    "stamp.sceneAlt": "할아버지가 맥스에게 선물을 건네요",
    "stamp.inspect": "선물을 눌러 확인해 보세요",
    "stamp.hintGift": "한 장",
    "stamp.nth": "{day}째 날",
    "stamp.parcelGift": "사료 한 봉지 · 순서표 1장 · 간식 10",
    "stamp.parcelLock": "{max}칸을 다 채우면 열려요",
    "yard.stoodHere": "마당에 <b>{item}</b>{particle} 생겼어요",
    "yard.placePrompt": "<b>{item}</b>{particle} 어디에 놓을까요?<br>마당을 눌러 자리를 정해 주세요",
    "yard.decorateDone": "🔨 꾸미기 끝",
    "yard.levelsUntil": "{item}까지 {count}판",
    "tutorial.bf1": "나비가 앉은 공부터 밀어요",
    "tutorial.bf1sub": "화살표 쪽으로 밀어 보세요",
    "tutorial.bf2": "잘했어요! 나비가 다음 공으로 가요",
    "tutorial.bf3": "나비가 길을 잃었어요",
    "tutorial.bf3sub": "한 수 무르면 다시 알려줘요",
    "tutorial.offPath": "<b>잘못된 방향</b>으로 움직였어요",
    "tutorial.undo": "<b>무르기</b>로 돌아갈 수 있어요",
    "tutorial.stuck": "벽에 붙은 공은 못 꺼내요<br><b>무르기</b>로 되돌려요",
    "tutorial.help": "<b>⚙</b> 안의 ❓로 이 설명을<br>언제든 다시 볼 수 있어요",
    "hud.walk": "산책",
    "fx.good1": "옳지!",
    "fx.good2": "딱이야!",
    "fx.good3": "좋아!",
    "fx.good4": "최고야!",
    "fx.yum": "냠!",
    "fx.allTreats": "다 주웠다!",
        "fx.streak": "{n}연속 한 번에!",
    "tutorial.bath1": "맥스가 통에 들어갔어요<br>이제 <b>거품</b>을 낼 차례예요",
    "tutorial.bath2": "<b>맥스를 여러 번 눌러</b> 주세요<br>거품이 다 차면 뽀송해져요",
    "tutorial.paint1": "색칠 작업대가 왔어요<br>마당 물건을 <b>다시 칠할</b> 수 있어요",
    "tutorial.paint2": "작업대를 <b>눌러</b> 보세요<br>몇 번을 바꿔도 <b>값은 안 들어요</b>",
    "tutorial.box1": "텃밭에서 거둔 게 모였어요<br>상자에 넣어 <b>보낼</b> 수 있어요",
    "tutorial.box2": "상자를 <b>눌러</b> 보내 주세요<br><b>내일</b> 답례가 옵니다",
    "tutorial.oak1": "참나무를 심었어요<br>하루 한 번 <b>물</b>을 줘야 자라요",
    "tutorial.oak2": "참나무를 <b>눌러</b> 물을 주세요<br><b>내일</b> 자라면서 도토리가 떨어져요",
    "tutorial.meal1": "맥스가 <b>배고파요</b><br>밥그릇에 밥을 채워 주세요",
    "tutorial.meal2": "빈 <b>밥그릇을 눌러</b> 주세요<br>맥스가 바로 먹어요",
    "tutorial.meal3": "오늘 몇 끼 먹었는지는<br>여기 <b>점</b>으로 볼 수 있어요",
    "tutorial.toggle": "여기서 표를 <b>켜고 끌 수</b> 있어요",
    "tutorial.first": "여기를 눌러<br><b>첫 산책</b>을 떠나요",
    "tutorial.goWalk": "산책 가기",
    "tutorial.goShop": "보러 가기",
    "tutorial.goYard": "마당 가기",
    "tutorial.viewYard": "마당 보기",
    "tutorial.shopOpen": "<b>할아버지의 선물</b>이 도착했어요!<br>선물과 필요한 물건을 확인해 보세요.",
    "tutorial.yardOpen": "<b>마당</b>이 열렸어요!",
    "tutorial.noteOpen": "<b>수첩</b>이 열렸어요!",
    "tutorial.goNote": "수첩 보기",
    "tutorial.noteBp": "간식을 다 모으면 설계도가 준비돼요",
    "tutorial.noteBuildFirst": "<b>설계도</b>가 준비됐어요<br>마당에 지을 수 있어요",
    "tutorial.noteBuild": "<b>설계도</b>가 준비됐어요<br>연필로 그려 보세요",
    "tutorial.errandOpen": "<b>아침 심부름</b>이 열렸어요!",
    "tutorial.goErrand": "심부름 보기",
    "tutorial.activate": "남은 <b>훈련 횟수</b>가<br>여기 보여요",
    "tutorial.turnOn": "켜기",
    "tutorial.practice": "연습",
    "tutorial.practice1": "맥스를 손가락으로 잡고<br>방석까지 죽 끌어 보세요!",
    "tutorial.dragOnly": "맥스를 손가락으로 잡고<br>방석까지 끌어 보세요",
    "tutorial.practice2": "맥스가 제일 좋아하는 공이에요!<br>공을 방석까지 밀어볼까요?",
    "tutorial.practice3": "맥스는 밀 수만 있어요<br>당기지는 못해요",
    "tutorial.practiceDone": "이제 진짜 산책을 나가볼까요?",
    "tutorial.hintSniff": "다람쥐가 앉은 수풀을 밀어 보세요",
    "tutorial.hintDest": "참새가 앉은 울타리를 밀어 보세요",
    "tutorial.hintOrder": "나비가 앉은 공을 밀면 돼요",
    "tutorial.giftStood": "마당에 {item}{particle} 생겼어요!",
    "tutorial.gift": "{item}{particle} 마당에 놓을 수 있어요!",
    "tutorial.firstGift": "마당이 열렸어요!\n{gift}",
    "yard.item.flower": "꽃밭",
    "yard.item.bowl": "물그릇",
    "yard.item.basket": "공 바구니",
    "yard.item.tree": "나무",
    "yard.item.bench": "벤치",
    "yard.more": "더 보기",
    "yard.item.house": "맥스 하우스",
    "yard.item.tree2": "꽃나무",
    "yard.item.mailbox": "우편함",
    "yard.item.pond": "연못",
    "yard.item.swing": "그네",
    "yard.item.colTeddy": "곰인형",
    "yard.item.colDisc": "원반",
    "yard.item.colSign": "할아버지 흔들의자",
    "yard.item.colShade": "밥·물그릇",
    "yard.item.colShoeRack": "맥스 방석",
    "yard.item.colTub": "물탱크 탑",
    "yard.item.colDuck": "고무오리",
    "yard.item.colBrush": "털 빗는 솔",
    "yard.item.colOak": "참나무",
    "yard.item.colDig": "비닐하우스",
    "yard.item.colTramp": "점프대",
    "yard.item.colBox": "배송 창고",
    "yard.item.colPaint": "색칠 헛간",
    "yard.item.colCatBed": "고양이 다방",
    "yard.item.colBrook": "오리집",
    "yard.item.colPin": "풍차",
    "yard.item.colRbrush": "무지개 붓",
    "yard.item.colSled": "썰매판",
    "yard.item.colCone": "솔방울",
    "yard.item.colDipper": "양철 바가지",
    "yard.item.colSoapBag": "비누 주머니",
    "yard.item.colSkip": "물수제비 돌",
    "yard.item.colLeafBoat": "나뭇잎 배",
    "yard.item.colStep": "징검돌",
    "yard.item.colCairn": "돌탑",
    "yard.item.colBall": "고무공",
    "yard.item.colStick": "물어오기 막대",
    "yard.item.colRope": "줄넘기",
    "yard.item.colScare": "허수아비",
    "yard.item.colTrowel": "모종삽",
    "yard.item.colSeedBox": "씨앗 상자",
    "yard.item.colCan": "깡통 장난감",
    "yard.item.colBlanket": "낡은 담요",
    "yard.item.colKey": "창고 열쇠",
    "yard.item.colPebble": "물감 조약돌",
    "yard.item.colPlank": "알록 팻말",
    "yard.item.colMarble": "구슬",
    "yard.item.colWand": "고양이 낚싯대",
    "yard.item.colLamp": "골목 가로등",
    "yard.item.colChime": "풍경",
    "yard.item.colBalloon": "바람 풍선",
    "yard.item.colVane": "풍향계 닭",
    "yard.item.colSlipper": "슬리퍼 한 짝",
    "yard.item.colTwig": "젖은 나뭇가지",
    "yard.item.colTennis": "찌그러진 테니스공",
    "yard.item.colCarrot": "당근",
    "yard.item.colTape": "택배 테이프",
    "yard.item.colSock": "물감 묻은 양말",
    "yard.item.colCatBell": "고양이 방울",
    "yard.item.colSeed": "민들레 씨",
    "yard.item.colFlag": "꼭대기 깃발",
    "yard.item.signYard": "맥스네 마당 표지판",
    "victory.goalStages": "{item}까지 <b>{count}판</b>",
    "victory.goalStage": "{item}까지 <b>{count}판</b>",
    "victory.goalStars": "{item}까지 간식 <b>{count}</b>개",
    "victory.goalAcorns": "{item}까지 <b>간식 {count}</b>",
    "victory.goalAcorn": "{item}까지 <b>간식 {count}</b>",
    "victory.souvenir": "{area} 큰 가구",
    "victory.gotLabel": "주웠어요",
    "victory.tapContinue": "화면을 눌러 계속",
    "victory.3.0": "완벽한 하루!",
    "victory.3.1": "천재 맥스 등장",
    "victory.3.2": "한 발자국도 낭비하지 않았어",
    "victory.3.3": "여유로운 산책이었어",
    "victory.2.0": "거의 완벽했어, 수고했어 멍!",
    "victory.2.1": "아슬아슬 세이프!",
    "victory.2.2": "꼬리가 절로 흔들리는 날",
    "victory.1.2": "공은 어디 안 가니까, 천천히",
    "victory.moon": "달빛 산책 끝!",
    "victory.moonFirst": "달빛 산책!",
    "victory.moonRepeat": "다시 달빛 산책",
    "victory.fireflies": " · 반딧불 ×{count}",
    "victory.pickup": "{place}에서 주웠어요",
    "victory.pickupAgain": "{place}에서 또 주웠어요",
    "victory.place.grass": "풀숲",
    "victory.place.bush": "덤불 밑",
    "victory.place.fence": "울타리 옆",
    "victory.place.path": "길가",
    "victory.place.soap": "비눗물 웅덩이 가",
    "victory.place.pit": "구덩이 옆",
    "victory.place.paint": "물감 자국 옆",
    "victory.place.water": "물가",
    "victory.place.hill": "언덕 아래",
    "victory.plus": "+{count}",
    "victory.acorns": "{count}개",
    "victory.acorn": "{count}개",
    "victory.double": "2배로 받기",
    "victory.doubled": "주머니가 두 배로!",
    "victory.adIncomplete": "광고를 다 못 봐서 2배를 못 받았어요",
    "victory.treasureAllSock": "보물 셋에 양말까지!",
    "victory.treasureAll": "보물을 전부 찾았다!",
    "victory.treasureSock": "양말에 속았다… {count}개!",
    "victory.treasureSome": "오늘은 {count}개! 내일 또 킁킁",
    "victory.steps": "걸음",
    "victory.treasures": "찾은 보물",
    "victory.par": "par",
    "victory.treasureWalk": "보물 산책",
    "victory.dailyDone": "오늘 심부름 하나 끝!",
    "victory.lunchDone": "오늘의 동네 한 바퀴 완주!",
    "victory.daily": "심부름",
    "victory.lunch": "동네 한 바퀴 · {day}",
    "victory.areaDone": "마당 완료!",
    "victory.chapterArt": "챕터 아트 획득",
    "victory.chipLabel": "조각",
    "victory.acornLabel": "간식",
    "victory.day.0": "월요일",
    "victory.day.1": "화요일",
    "victory.day.2": "수요일",
    "victory.day.3": "목요일",
    "victory.day.4": "금요일",
    "victory.day.5": "토요일",
    "victory.day.6": "일요일",
    "growth.1.step.1": "천막 잠자리",
    "growth.1.step.2": "뼈대 세우기",
    "growth.1.step.3": "맥스 하우스 완성",
    "growth.1.step.4": "그늘 천막",
    "growth.1.step.5": "나무 마루",
    "growth.1.step.6": "장작더미와 등불",
    "growth.1.name": "맥스 하우스",
    "growth.1.buildTitle": "맥스 하우스 만들기",
    "growth.2.step.1": "돌 바닥과 통",
    "growth.2.step.2": "받침 골조",
    "growth.2.step.3": "물탱크 탑",
    "growth.2.step.4": "거품과 비누",
    "growth.2.step.5": "흰 발판과 수건걸이",
    "growth.2.step.6": "놋쇠 꼭지와 등",
    "growth.2.name": "물탱크 탑",
    "growth.2.buildTitle": "물탱크 탑 만들기",
    "growth.3.step.1": "마른 웅덩이",
    "growth.3.step.2": "물과 발판",
    "growth.3.step.3": "오리집",
    "growth.3.step.4": "첫 오리",
    "growth.3.step.5": "흰 돌과 수련",
    "growth.3.step.6": "오리 둘과 등불",
    "growth.3.name": "오리집",
    "growth.3.buildTitle": "오리집 만들기",
    "growth.4.step.1": "도토리",
    "growth.4.step.2": "참나무 새싹",
    "growth.4.step.3": "나무 위 오두막",
    "growth.4.step.4": "작은 새집",
    "growth.4.step.5": "밑동 회칠과 두름돌",
    "growth.4.step.6": "단풍과 등불",
    "growth.4.name": "참나무",
    "growth.4.buildTitle": "참나무 키우기",
    "growth.5.step.1": "둥근 틀",
    "growth.5.step.2": "점프 천",
    "growth.5.step.3": "점프대",
    "growth.5.step.4": "발바닥 문양",
    "growth.5.step.5": "알록 스프링",
    "growth.5.step.6": "놋쇠 손잡이 봉",
    "growth.5.name": "점프대",
    "growth.5.buildTitle": "점프대 만들기",
    "growth.6.step.1": "돌 기초와 비닐",
    "growth.6.step.2": "비닐하우스 골조",
    "growth.6.step.3": "비닐하우스",
    "growth.6.step.4": "수확 바구니",
    "growth.6.step.5": "흰 상자밭과 팻말",
    "growth.6.step.6": "놋쇠 물뿌리개",
    "growth.6.name": "비닐하우스",
    "growth.6.buildTitle": "비닐하우스 만들기",
    "growth.7.step.1": "돌 기초와 널빤지",
    "growth.7.step.2": "창고 골조",
    "growth.7.step.3": "배송 창고",
    "growth.7.step.4": "배송 표지판",
    "growth.7.step.5": "흰 우편함",
    "growth.7.step.6": "건초와 도구",
    "growth.7.name": "배송 창고",
    "growth.7.buildTitle": "배송 창고 만들기",
    "growth.8.step.1": "작업대",
    "growth.8.step.2": "물감 세트",
    "growth.8.step.3": "색칠 헛간",
    "growth.8.step.4": "알록 울타리",
    "growth.8.step.5": "색상표와 화분",
    "growth.8.step.6": "무지개 차양과 등",
    "growth.8.name": "색칠 헛간",
    "growth.8.buildTitle": "색칠 헛간 만들기",
    "growth.9.step.1": "고양이 발자국",
    "growth.9.step.2": "담 너머 눈길",
    "growth.9.step.3": "고양이 다방",
    "growth.9.step.4": "물그릇과 방울",
    "growth.9.step.5": "이름표와 팻말",
    "growth.9.step.6": "짙은 원목 밥상",
    "growth.9.name": "고양이 다방",
    "growth.9.buildTitle": "고양이 다방 만들기",
    "growth.10.step.1": "기둥",
    "growth.10.step.2": "바람개비 날개",
    "growth.10.step.3": "풍차",
    "growth.10.step.4": "바람 리본",
    "growth.10.step.5": "작은 바람개비 무리",
    "growth.10.step.6": "놋쇠 날개와 등",
    "growth.10.name": "풍차",
    "growth.10.buildTitle": "풍차 만들기",
    "growth.starTitle": "{area} 간식 모으기",
    "growth.mystery": "아직 못 본 단계",
    "growth.unlockStage": "{stage}판을 걸으면 열려요",
    "growth.goal.first": "첫 꾸러미까지",
    "growth.goal.next": "다음 꾸러미까지",
    "growth.goal.deluxe": "최고급까지",
    "victory.giftRecipe": "<b>{name}</b> 설계도",
    "victory.giftBundle": "{mat} {n}개 · 간식 {paw}개",
    "victory.giftAcorn": "간식 {paw}개",
    "victory.clearAuto": "산책을 마쳤어요",
    "part.base": "바탕",
    "part.body": "몸통",
    "part.top": "마무리",
    "growth.partN": "부품 {n} / 3",
    "growth.partWait": "다음에",
    "growth.make": "만들기",
    "growth.makeN": "{part} 만들기",
    "growth.needLabel": "필요",
    "growth.bom": "자재",
    "growth.bomUsed": "들어간 자재",
    "growth.pourSub": "{put}개 넣으면 {rest}개 남아요",
    "growth.pourAll": "넣기",
    "growth.build": "짓기",
    "growth.stampDone": "완성",
    "growth.nextTitle": "다음 설계도",
    "growth.lack": "{n}개 모자람",
    "growth.from2": "{mat}{particle} {places}에서 나와요",
    "growth.buildStep": "{label} 짓기",
    "growth.buildNow": "짓기",
    "growth.putN": "{mat} {n}개 넣기",
    "growth.putSome": "가진 {n}개만 넣기",
    "growth.putNone": "{mat}{particle} 없어요",
    "growth.short": "{mat}{particle} {n}개 모자라요 · {places}에서 나와요",
    "growth.lastPart": "넣으면 {label} 완성",
    "growth.builtToast": "{label} 완성 · {n}/{tot}",
    "growth.planTag": "설계도",
    "growth.allBuilt": "다 지었어요",
    "growth.nextAt": "다음 설계도는 {stage}판 꾸러미에서",
    "growth.short": "{mat}{particle} {n}개 모자라요",
    "growth.from": "{places}에서 나와요",
    "growth.pieces": "{got}/{total}",
    "growth.piecesOf": "{name} {got}/{total}",
    "growth.stageUnit": "판",
    "growth.stageUnit.one": "판",
    "tool.noTarget": "여기선 쓸 자리가 없어요",
    "hint.unlocked": "할아버지의 훈련 추가!",
    "common.tapContinue": "눌러서 계속",
    "game.noMoves": "걸음을 다 썼어요",
    "game.exitQuestion": "산책을 그만 둘까요?",
    "game.keepTrying": "조금 더 해볼래요",
    "game.skipAd": "광고 보고 건너뛰기",
    "game.skipLimit": "동네마다 한 번씩 쓸 수 있어요",
    "menu.bag": "주머니",
    "common.nice": "좋아요",
    "menu.decorations": "장식",
    "menu.decorate": "🔨 꾸미기",
    "yard.plantQuestion": "무엇을 심을까요?",
    "yard.paintQuestion": "무엇을 칠할까요?",
    "yard.paintApply": "칠하기",
    "yard.paintCurrent": "사용 중",
    "yardShort.playDays": "{count}일 더 놀기",
    "yardShort.sameCrop": "같은 작물 {max}개",
    "yard.harvested": "<b>{name} {count}개</b>를 수확했어요!",
    "yardShort.mealWait": "{time}",
    "yardShort.growWait": "자라기까지 {time}",
    "yardShort.parcelWait": "답례까지 {time}",
    "common.walk": "산책 가기",
    "common.free": "무료",
    "common.skip": "건너뛰기",
    "common.cancel": "그만둘래요",
    "common.unlockAfter": "{stage}까지 걸으면",
    "hint.sniff.name": "밟아!",
    "hint.dest.name": "점프!",
    "hint.order.name": "갖고와!",
    "hint.sniff.short": "밟아",
    "hint.dest.short": "점프",
    "hint.order.short": "갖고와",
    "hint.sniff.description": "주변 <b>수풀</b>을 밟아 길로 만들어요",
    "hint.dest.description": "주변 <b>공</b>을 뛰어넘어 건너편 땅에 내려요",
    "hint.order.description": "주변 <b>공</b>을 물어다 맥스 <b>주변</b>에 놔요",
    "hint.sniff.how": "울타리는 못 밟아요",
    "hint.dest.how": "공은 그대로 있어요",
    "hint.order.how": "방석 위엔 못 놔요",
    "hint.sniff.coach": "밟을 수풀을 고르세요",
    "hint.dest.coach": "내려앉을 땅을 고르세요",
    "hint.order.coach": "공을 고르고, 놓을 자리를 고르세요",
    "story.intro1": "<b>할아버지의 농장에는<br>맥스가 살아요.</b>",
    "story.intro2": "<b>맥스는 할아버지와<br>장난감 놀이를 좋아해요.</b>",
    "story.intro1.alt": "할아버지의 농장에 사는 맥스",
    "story.intro2.alt": "할아버지와 함께 닭 장난감을 방석에 밀어 넣는 맥스",
    "callout.cartH.name": "가로 대차",
    "callout.cartH.text": "좌우로만 밀 수 있어요",
    "map.leftMat": "두고 온 간식 {n}판",
    "map.leftGo": "가기",
    "map.districtLocked": "다 걸으면 다음 동네가 열려요",
    "map.woof": "멍멍!",
    "guide.base.name": "산책 시작",
    "guide.base.text": "공을 <b>방석까지 밀어 넣으세요</b>",
    "guide.ice.name": "비눗물",
    "guide.ice.text": "공은 비눗물 끝까지 <b>미끄러져요</b>",
    "guide.slope.name": "언덕",
    "guide.slope.text": "공은 화살표 방향으로 <b>굴러가요</b>",
    "guide.slopeback.name": "역방향 언덕",
    "guide.slopeback.text": "반대로 밀어도 화살표 방향으로 <b>굴러가요</b>",
    "guide.billiard.name": "쿵!",
    "guide.billiard.text": "공끼리 부딪히면 앞 공이 <b>밀려나요</b>",
    "guide.slopebilliard.name": "언덕 쿵",
    "guide.slopebilliard.text": "굴러간 공도 다른 공을 <b>밀어요</b>",
    "guide.trampknock.name": "폴짝 쿵",
    "guide.trampknock.text": "착지 칸의 공을 <b>한 칸 밀어내요</b>",
    "guide.trampback.name": "폴짝 되튐",
    "guide.trampback.text": "막히면 <b>가까운 칸에</b> 내려요|둘 다 막히면 <b>트램플린에</b> 멈춰요",
    "guide.pit.name": "구덩이",
    "guide.pit.text": "공이 빠지면 <b>길이 돼요</b>",
    "guide.bone.name": "뼈다귀",
    "guide.bone.text": "뼈다귀를 물어 구덩이에 <b>묻으세요</b>|묻은 자리는 다시 지나갈 수 없어요",
    "guide.furrow.name": "좁은 고랑길",
    "guide.furrow.text": "고랑길은 <b>맥스만</b> 지나갈 수 있어요",
    "guide.dpit.name": "구덩이",
    "guide.dpit.text": "공이 빠지면 <b>길이 돼요</b>",
    "guide.crop.name": "작물 심기",
    "guide.crop.text": "작물을 구덩이에 <b>심으세요</b>|심은 곳은 <b>길이 돼요</b>",
    "guide.dureong.name": "흙더미",
    "guide.dureong.text": "맥스가 밀면 <b>한 칸 가고 흙이 줄어요</b>|<b>세 번</b> 밀면 사라져요|구덩이에 넣으면 <b>길이 돼요</b>",
    "guide.cart.name": "세로 대차",
    "guide.cart.text": "<b>위아래로만</b> 밀 수 있어요",
    "guide.cartH.name": "가로 대차",
    "guide.cartH.text": "<b>좌우로만</b> 밀 수 있어요",
    "guide.color.name": "색 맞추기",
    "guide.color.text": "공을 <b>같은 색 방석</b>에 넣으세요",
    "guide.paint.name": "페인트",
    "guide.paint.text": "공은 지나간 <b>페인트 색으로 변해요</b>|같은 색 방석에 넣으세요",
    "guide.log.name": "택배 박스",
    "guide.log.text": "박스는 <b>한 칸씩</b> 밀려요",
    "guide.logpit.name": "상자로 길 만들기",
    "guide.logpit.text": "박스를 구덩이에 넣으면 <b>길이 돼요</b>",
    "guide.valve.name": "호스",
    "guide.valve.text": "밸브를 누르면 <b>물줄기가 멈춰요</b>",
    "guide.logvalve.name": "박스와 호스",
    "guide.logvalve.text": "박스로 누른 밸브는 <b>계속 잠겨요</b>",
    "guide.flow.name": "물살",
    "guide.flow.text": "공은 물살을 따라 흘러요|맥스는 물에 못 들어가요|물가의 공은 <b>반대로</b> 다시 넣을 수 있어요",
    "guide.pool.name": "웅덩이",
    "guide.pool.text": "공은 웅덩이에 <b>갇혀요</b>|다른 공으로 <b>쿵!</b> 하면 빠져나와요",
    "guide.bridge.name": "다리",
    "guide.bridge.text": "땅의 공은 <b>다리 위로</b>|물살의 공은 <b>다리 아래로</b> 지나가요",
    "guide.bridge.over": "땅의 공은 <b>다리 위로</b> 건너가요|다리에선 안 멈춰서 그대로 <b>쿵</b> 이어져요",
    "guide.bridge.under": "물살에 실린 공은 <b>다리 아래로</b> 지나가요",
    "guide.catbox.name": "율무",
    "guide.catbox.text": "공이 닿으면 <b>다음 빈 상자로</b> 숨어요|율무가 숨어 있는 칸은 <b>못 지나가요</b>",
    "guide.greedy.name": "수수",
    "guide.greedy.text": "방석 → 공 → 통으로 <b>옮겨 앉아요</b>|수수가 앉은 곳은 <b>쓸 수 없어요</b>|통은 <b>맥스만</b> 지나가요",
    "guide.twocats.name": "율무와 수수",
    "guide.twocats.text": "율무는 <b>상자로</b>, 수수는 <b>통으로</b> 옮겨요",
    "guide.wind.name": "바람개비",
    "guide.wind.text": "한 바퀴 돌면 공이 깃발 쪽으로 <b>한 칸 밀려요</b>",
    "guide.windbox.name": "바람 막기",
    "guide.windbox.text": "상자와 방석 위 공은 바람에 <b>밀리지 않아요</b>",
    "guide.windpush.name": "바람 타기",
    "guide.windpush.text": "바람이 부는 걸음에 밀면 <b>한 칸 더 가요</b>",
    "guide.napcat.name": "지켜보는 고양이",
    "guide.napcat.text": "맥스가 화단 옆을 떠나면 그 자리에 앉아요|공으로 밀면 <b>화단으로 돌아가요</b>",
    "guide.catwalk.name": "지켜보는 고양이",
    "guide.catwalk.text": "맥스가 걸을 때마다 <b>한 칸씩</b> 움직여요|앞이 막히면 돌아서요",
    "guide.tramp.name": "트램플린",
    "guide.tramp.text": "공은 <b>한 칸을 뛰어넘어요</b>",
    'app.title': '맥스야 산책 가자',
    'app.subtitle': 'WALK WITH MAX',
    'common.next': '다음',
    'common.ok': '알았어요',
    'common.close': '닫기',
    'common.back': '뒤로',
    'common.start': '시작하기',
    'common.lookAround': '둘러보기',
    'common.later': '나중에',
    'common.continue': '계속 걷기',
    'common.exit': '나가기',
    'common.retry': '다시하기',
    'common.undo': '무르기',
    'settings.title': '설정',
    'settings.sound': '효과음',
    'settings.music': '음악',
    'settings.vibration': '진동',
    'settings.directionButtons': '방향 버튼',
    'settings.buttonSide': '버튼 위치',
    'settings.left': '왼쪽',
    'settings.right': '오른쪽',
    'settings.reset': '진행 초기화',
    'settings.privacy': '개인정보처리방침',
    'settings.language': '언어',
    'accessibility.help': '도움말',
    'accessibility.settings': '설정',
    'accessibility.exit': '나가기',
    'accessibility.close': '닫기',
    'accessibility.back': '뒤로',
    'accessibility.up': '위',
    'accessibility.down': '아래',
    'accessibility.left': '왼쪽',
    'accessibility.right': '오른쪽',
    'rotate.title': '휴대폰을 세로로 돌려주세요',
    'rotate.body': '맥스의 산책길은 세로 화면에 가장 잘 보여요',
    'district.1.name': '맥스네 마당',
    'district.2.name': '뽀득 뒷마당',
    'district.3.name': '졸졸 냇가',
    'district.4.name': '도토리 동산',
    'district.5.name': '폴짝 공터',
    'district.6.name': '쑥쑥 텃밭',
    'district.7.name': '덜컹 창고',
    'district.8.name': '알록 울타리길',
    'district.9.name': '냥냥 골목',
    'district.10.name': '바람개비 들판',
    'district.11.name': '잔치마당',
    'district.12.name': '솔숲길',
    'district.13.name': '배달길',
    'district.14.name': '달빛길',
    'district.15.name': '여름맞이',
    'chapter.unknown': '산책',
    'chapter.1.name': '밀기',
    "chapter.6.name": "공 둘",
    'chapter.11.name': '공 둘',
    'chapter.16.name': '공 둘 심화',
    'chapter.21.name': '공 셋',
    'chapter.26.name': '밀기 총정리',
    'chapter.31.name': '비눗물',
    'chapter.36.name': '비눗물 심화',
    'chapter.41.name': '쿵!',
    'chapter.46.name': '쿵! 심화',
    'chapter.51.name': '비눗물 공 셋',
    'chapter.56.name': '뒷마당 총정리',
    'chapter.61.name': '물살',
    'chapter.66.name': '물가',
    'chapter.71.name': '웅덩이',
    'chapter.76.name': '웅덩이 응용',
    'chapter.81.name': '다리',
    'chapter.86.name': '냇가 총정리',
    'chapter.91.name': '언덕',
    'chapter.96.name': '언덕 심화',
    'chapter.101.name': '언덕 쿵',
    'chapter.106.name': '언덕 쿵 심화',
    'chapter.111.name': '언덕 공 셋',
    'chapter.116.name': '뒷동산 총정리',
    'chapter.121.name': '트램플린',
    'chapter.126.name': '폴짝 쿵',
    'chapter.131.name': '폴짝 쿵 심화',
    'chapter.136.name': '폴짝 되튐',
    'chapter.141.name': '폴짝 되튐 심화',
    'chapter.146.name': '폴짝 총정리',
    'chapter.151.name': '구덩이',
    'chapter.156.name': '작물 심기',
    'chapter.161.name': '작물 심화',
    'chapter.166.name': '흙더미',
    'chapter.171.name': '흙더미와 작물',
    'chapter.176.name': '밭두렁 총정리',
    'chapter.181.name': '택배 상자',
    'chapter.186.name': '상자 둘',
    'chapter.191.name': '세로 손수레',
    'chapter.196.name': '가로와 세로',
    'chapter.201.name': '상자와 손수레',
    'chapter.206.name': '창고 총정리',
    'chapter.211.name': '페인트',
    'chapter.216.name': '페인트 심화',
    'chapter.221.name': '호스 물주기',
    'chapter.226.name': '호스 심화',
    'chapter.231.name': '택배 물들이기',
    'chapter.236.name': '공방 총정리',
    'chapter.241.name': '숨는 고양이',
    'chapter.246.name': '상자 셋',
    'chapter.251.name': '욕심쟁이 고양이',
    'chapter.256.name': '욕심쟁이 심화',
    'chapter.261.name': '두 고양이',
    'chapter.266.name': '골목 총정리',
    'chapter.271.name': '바람',
    'chapter.276.name': '깃발 골목',
    'chapter.281.name': '상자로 세우기',
    'chapter.286.name': '걸음 세기',
    'chapter.291.name': '바람 타기',
    'chapter.296.name': '들판 총정리',
    'chapter.301.name': '잔치 물감',
    'chapter.306.name': '잔치 언덕',
    'chapter.311.name': '잔치 물줄기',
    'chapter.316.name': '잔치 마무리',
    'chapter.321.name': '솔숲 구덩이',
    'chapter.326.name': '솔숲 비눗물',
    'chapter.331.name': '솔숲 뼈다귀',
    'chapter.336.name': '솔숲 언덕',
    'chapter.341.name': '배달 밀기',
    'chapter.346.name': '배달 순찰',
    'chapter.351.name': '배달 폴짝',
    'chapter.356.name': '배달 비눗물',
    'chapter.361.name': '달빛 폴짝',
    'chapter.366.name': '달빛 물감',
    'chapter.371.name': '달빛 언덕',
    'chapter.376.name': '집으로',
    'chapter.381.name': '여름 비눗물',
    'chapter.391.name': '여름 언덕',
    'chapter.401.name': '여름 물감',
    'chapter.411.name': '여름 택배',
    'chapter.421.name': '여름 폴짝',
    'story.artLabel': '{area} 풍경',
    'story.district.1': '할아버지가 농장 문을 열었어요.\n맥스가 앞마당으로 달려가요.',
    'story.district.2': '오늘은 농장을 청소하는 날이에요.\n맥스도 거품 속으로 뛰어들어요.',
    'story.district.3': '돌다리 아래로 맑은 냇물이 흘러요.\n건너편까지 산책길이 이어져요.',
    'story.district.4': '할아버지가 자주 걷던 뒷동산이에요.\n이번엔 맥스가 앞장서요.',
    'story.district.5': '할아버지가 공터를 놀이마당으로 꾸몄어요.\n맥스가 첫 손님이에요.',
    'story.district.6': '할아버지가 아끼는 밭에 심을 때예요.\n맥스와 첫 농사를 시작해요.',
    'story.district.7': '오래 잠긴 덜컹 창고가 열렸어요.\n안에는 옮길 상자가 가득해요.',
    'story.district.8': '골목에 알록달록 페인트 향이 퍼져요.\n회색 공도 새 옷을 입어요.',
    'story.district.9': '농장 뒤 골목에 고양이들이 살기 시작했어요.\n낯선 손님에 귀가 쫑긋 섰어요.',
    'story.district.10': '멀리 돌아온 바람이 들판에 닿았어요.\n긴 산책도 바람 끝까지 이어져요.',
    'language.ko': '한국어',
    'language.en': 'English',
"nav.shop": "상점",
"nav.walk": "산책",
"nav.yard": "동네",
"notice.dailyLocked": "50번 걸으면 일과표가 열려요 (지금 {count}번)",
"notice.dailyDone": "오늘은 다녀왔어요 — 내일 또 만나요",
"notice.dailySoon": "동네 한 바퀴는 곧 열려요",
"notice.adDaily": "광고를 다 못 봐서 한 번을 못 열었어요",
"notice.noDaily": "오늘은 더 걸을 데가 없어요",
"notice.devAd": "<b>[{slot}]</b> 광고 자리 — 개발 중이라 바로 드려요",
"ad.clear2x": "클리어 2배",
"ad.hint": "훈련 한 번",
"ad.skip": "판 건너뛰기",
"ad.daily": "데일리 한 번 더",
"ad.meal": "밥 한 끼",
    "billing.verify": "결제를 확인하지 못했어요",
    "billing.pending": "결제가 완료되면 간식이 들어와요",
    "billing.unavailable": "간식은 출시 앱에서 구매할 수 있어요",
    "billing.failed": "결제를 완료하지 못했어요. 다시 시도해 주세요",
    "billing.duplicate": "이미 받은 상품이에요",
    "billing.received": "간식 {count}개가 들어왔어요",
    "billing.arrived": "간식이 도착했어요!",
    "billing.balanceChange": "내 간식 {before} → {after}",
    "billing.collect": "받기",
    "billing.thanks": "고마워요!",
    "billing.adfree": "광고 없이 산책할 수 있어요",
    "shop.hints": "할아버지의 훈련",
    "shop.feed": "사료",
    "shop.acorns": "간식",
    "shop.stock": "내 주머니 · {count}장",
    "shop.singleHint": "{name} 1장",
    "shop.none": "없음",
    "shop.half": "반 봉지",
    "shop.full": "한 봉지",
    "shop.meals": "{count}끼",
    "shop.buy": "<b>{name}</b>{particle} 살까요?",
    "shop.hintN": "{name} {count}번",
    "shop.cards": "{count}개",
    "shop.inbag": "가진 것 {count}개",
    "shop.confirm": "구매",
    "shop.back": "돌아가기",
    "shop.refill": "간식 채우기",
    "shop.from": "필요한 만큼 골라요",
    "shop.viewPacks": "3가지 보기",
    "shop.hidePacks": "접기",
    "shop.popular": "많이 골라요",
    "shop.quantity": "{count}개",
    "shop.paw1": "한 병",
    "shop.paw2": "한 통",
    "shop.paw3": "한 상자",
    "shop.permanent": "맥스에게",
    "shop.once": "한 번만 사면 계속 남아요 — 구독이 아니에요",
    "shop.owned": "가지고 있어요",
    "shop.have": "보유",
    "shop.gift": "선물 받기",
    "shop.group.fur": "털색",
    "shop.group.wear": "착용",
    "shop.group.mat": "방석 무늬",
    "shop.layer": "머리·목에 겹쳐 착용",
    "shop.fur_white": "백구",
    "shop.fur_yellow": "황구",
    "shop.fur_black": "흑구",
    "shop.fur_tri": "삼색이",
    "shop.neck_scarf": "빨간 스카프",
    "shop.neck_bell": "목 방울",
    "shop.head_hat": "밀짚모자",
    "shop.neck_gold": "금빛 목걸이",
    "shop.mat_plain": "기본",
    "shop.mat_dot": "물방울",
    "shop.mat_check": "체크",
    "shop.mat_star": "별무늬",
    "shop.goldLock": "챕터 3개 만개",
    "shop.cheer": "맥스 응원하기",
    "shop.cheerSub": "광고 없이 + 한정 목걸이",
    "shop.yard": "동네 마당 장식",
    "shop.yardSub": "사면 곳간에 들어가요 — 동네에서 점선 자리를 눌러 놓아요",
    "shop.claim": "받기",
    "shop.zoneLock": "{name} 개간 후",
    "shop.wardrobe": "옷장",
    "shop.play": "놀이",
    "shop.season": "계절",
    "meal.empty": "밥그릇이 비었어요<br><b>한 끼 채워 줄까요?</b>",
    "meal.remaining": "{count}끼 남았어요<br><b>미리 채워 둘까요?</b>",
    "meal.next": "다음 밥때까지 {time}",
    "meal.adLeft": "오늘 {count}번 남았어요",
    "meal.adDone": "오늘은 다 봤어요",
    "meal.first": "첫 봉지는 그냥 드려요",
    "meal.half": "사료 반 봉지",
    "meal.full": "사료 한 봉지",
    "meal.ad": "광고 보고 한 끼",
    "meal.adLimit": "하루 세 번까지",
    "meal.wait": "기다렸다 와도 괜찮아요",
    "meal.addHalf": "사료 반 봉지를 부었어요",
    "meal.addFull": "사료를 부었어요",
    "meal.filled": "사료를 부었어요 — 밥그릇이 가득!",
    "meal.bought": "사료를 사서 부었어요",
    "meal.one": "밥 한 끼를 받았어요",
    "notice.short": "간식이 {count}개 모자라요",
    "notice.hintShort": "간식 {count}개 모자라요<br>산책길에서 주워 모아요",
    "notice.undoLimit": "이 판에서 무르기는 여기까지예요",
    "notice.restartLimit": "이 판은 여기까지예요<br>나갔다 오면 다시 걸을 수 있어요",
    "notice.walkOn": "이어 걷기",
    "notice.retry": "다시 걷기",
    "notice.more": "{count}걸음 더",
    "notice.addMoves": "{count}걸음 더 걸을 수 있어요",
    "notice.next": "다음 판으로",
    "notice.quitMeal": "여기까지 걸은 건 사라지고<br>다시 들어올 때 한 끼를 써요",
    "notice.quit": "여기까지 걸은 건 사라져요",
    "notice.notReady": "이번 산책은 아직 준비 못 했어요",
    "notice.noHints": "표가 없어요 — 간식가게에서 채울 수 있어요",
    "notice.bagAdded": "훈련 횟수가 늘었어요",
    "notice.hintActive": "채웠어요 — 켜 뒀어요",
    "notice.pickBall": "먼저 <b>공</b>을 눌러 주세요",
    "notice.full": "밥그릇이 가득이에요",
    "notice.adMeal": "광고를 다 못 봐서 밥을 받지 못했어요",
    "notice.adSkip": "광고를 다 못 봐서 건너뛰지 못했어요",
    "notice.shopLocked": "2-10을 걸으면 간식가게가 열려요",
    "notice.shopPlaying": "산책이 끝나면 가게에 갈 수 있어요<br>지금 간식 {count}개",
    "notice.yardLocked": "30번 걸으면 마당이 열려요 (지금 {count}번)",
    "notice.yardSoon": "마당은 아직 준비 중이에요",
    "hud.stepsLeft": "남은 걸음",
    "map.hardWalk": "험한 길",
    "lvcard.title": "{lv}번째 산책",
    "lvcard.titleFirst": "첫 산책",
    "lvcard.rowMat": "간식",
    "lvcard.grpReward": "보상",
    "lvcard.rowBase": "클리어",
    "lvcard.rowHint": "훈련",
    "victory.giftTap": "눌러서 열기",
    "victory.giftPaw": "간식 {count}개",
    "notice.par": "가장 짧은 길을 넘었어요<br>돌아가도 괜찮아요 — 걸음은 넉넉해요",
    "notice.lamp": "어두우면 화면을 <b>탭</b>해서 손전등을 켜 보세요",
    "time.hours": "{count}시간",
    "time.minutes": "{count}분",
    "time.reset": "자정에 새로 와요 · {time}",
    "note.caseFrom": "{n}판에서 주웠어요",
    "note.caseUnknown": "아직 못 찾았어요",
    "note.caseMake": "{item} 만들기",
    "note.caseDone": "{item} 완성!",
    "note.bpMake": "설계도 만들기",
    "note.bpLack": "조각 {n}개 모자라요",
    "note.bpFrom": "그 동네 판 10개를 깰 때마다 설계도가 나와요",
    "note.bpDone": "{item} 설계도가 생겼어요!",
    "note.bpNew": "새 조각 {n}개",
    "note.casePut": "{name}에 놓으러 가기",
    "note.caseStanding": "{name}에 서 있어요",
    "note.caseYardLocked": "{name}{particle} 완주하면 놓을 수 있어요",
    "victory.bpPick": "{item} — 맥스가 물어 온 장난감이에요",
    "victory.bpSub": "수첩 진열장에서 만들어요",
    "chore.c1a": "마당 쓸기",
    "chore.c1b": "밥그릇 채우기",
    "chore.c1c": "창 닦기",
    "chore.c2a": "수건 널기",
    "chore.c2b": "물 갈기",
    "chore.c2c": "거품 목욕",
    "chore.c3a": "낙엽 건지기",
    "chore.c3b": "돌 쌓기",
    "chore.c3c": "물레방아 돌리기",
    "chore.c4a": "도토리 줍기",
    "chore.c4b": "새 모이 주기",
    "chore.c4c": "등불 켜기",
    "chore.c5a": "폴짝 놀이",
    "chore.c5b": "먼지 털기",
    "chore.c5c": "스프링 조이기",
    "chore.c6a": "물 주기",
    "chore.c6b": "거두기",
    "chore.c6c": "잡초 뽑기",
    "chore.c7a": "상자 나르기",
    "chore.c7b": "표지판 돌리기",
    "chore.c7c": "우편함 비우기",
    "chore.c8a": "붓 씻기",
    "chore.c8b": "울타리 덧칠",
    "chore.c8c": "색상표 맞추기",
    "chore.c9a": "밥 챙겨 주기",
    "chore.c9b": "물 갈아 주기",
    "chore.c9c": "이름표 닦기",
    "chore.c10a": "날개 닦기",
    "chore.c10b": "리본 갈기",
    "chore.c10c": "등 켜기",
    "chore.cond.walk": "오늘 {n}판",
    "chore.cond.star3": "간식 셋 남긴 판 {n}",
    "chore.cond.par": "par 안에 {n}판",
    "chore.cond.new": "새 판 {n}",
    "chore.every3": "사흘에 한 번",
    "chore.verb.house": "밥 채우기",
    "chore.verb.colTub": "씻기기",
    "chore.verb.colBrook": "낙엽 건지기",
    "chore.verb.colOak": "도토리 줍기",
    "chore.verb.colTramp": "공 던지기",
    "chore.verb.colDig": "텃밭 돌보기",
    "chore.verb.colBox": "택배 보내기",
    "chore.verb.colPaint": "초상화 그리기",
    "chore.verb.colCatBed": "고양이 보기",
    "chore.verb.colPin": "걸린 것 떼기",
    "chore.today": "오늘 마당일",
    "chore.didToday": "오늘 다 했어요",
    "chore.noneToday": "오늘 마당은 조용해요",
    "chore.claim": "받기",
    "chore.none": "집을 지으면 일이 늘어요",
    "chore.noneWeek": "이번 주 일은 아직 없어요",
    "set.fetch": "장난감",
    "set.fetchFrame": "맥스의 장난감들",
    "set.frameHung": "액자가 걸렸어요",
    "set.fetchStory": "열 동네에서 하나씩. 다 맥스 게 아니었는데, 이제 다 맥스 거예요.",
    "note.new.bp": "수첩에 <b>설계도</b>가 쌓여요!",
    "note.new.case": "수첩에 <b>진열장</b>이 생겼어요!",
    "note.new.album": "수첩에 <b>앨범</b>이 붙었어요!",
    "note.new.chores": "수첩에 <b>일과표</b>가 생겼어요!",
    "note.new.cal": "수첩에 <b>달력</b>이 생겼어요!",
    "note.build": "설계도",
    "note.case": "진열장",
    "note.album": "앨범",
    "note.albumEmpty": "동네 하나를 끝내면 그림이 붙어요",
    "note.albumDone": "함께 걸은 마을",
    "note.chores": "일과표",
    "chore.go": "하러 가기",
    "chore.rwToday": "{mat} 나와요",
    "chore.rwLater": "{mat} {n}일 뒤",
    "chore.rwDropped": "{mat} 떨어져 있어요",
    "chore.rwMeal": "밥 {n}끼",
    "chore.rwCrop": "{name} {n}개",
    "chore.rwCare": "들른 날 +1",
    "note.bp": "설계도",
    "note.bpGo": "설계도에서 만들기",
    "note.bpSecCol": "작은 가구 설계도",
    "note.bpSecPlan": "큰 가구 설계도",
    "note.bpBuilt": "마당에 지었어요",
    "note.infoBig": "{n} / {t}칸 지었어요",
    "note.infoOwn": "마당에 놓을 수 있어요",
    "note.infoBp": "설계도가 준비됐어요",
    "note.infoBpYard": "설계도가 준비됐어요 · 이 동네 마당이 열리면",
    "note.infoLater": "앞의 가구를 먼저 모으면 열려요",
    "note.bpLater": "다음 차례",
    "note.planStep": "{n}단계 · {label}",
    "note.planGo": "{lv}판 가기",
    "note.caseToyFrom": "판을 처음 깨면 맥스가 장난감을 물어 와요",
    "note.lockBp": "조각이나 설계도가 생기면 열려요",
    "victory.chipGot": "{item} 조각 +1",
    "victory.chipSub": "조각 {n} / {t} · 셋이면 설계도 한 장",
    "victory.chipReady": "조각이 다 모였어요 — 수첩 설계도에서 만들어요",
    "note.bigYardLater": "설계도가 준비됐어요 · 마당이 열리면",
    "growth.hammerHint": "망치를 누르면 지어요",
    "note.choresOpened": "<b>일과표</b>가 열렸어요<br>매일 마당을 돌보면 간식이 와요",
    "note.planNeed": "{mats} 더 모으면 지을 수 있어요",
    "note.planYardReady": "설계도가 준비됐어요",
    "note.yardGo": "지을 곳 보기",
    "victory.planNote": "설계도가 수첩에 들어갔어요",
    "victory.planNoteSub": "도토리를 모으면 마당에 지어요",
    "victory.noteGo": "수첩 보기",
    "tutorial.matFirst": "설계도에 쓸 <b>간식</b>이에요",
    "tutorial.matWall": "수풀·울타리에도 <b>간식</b>이 걸려 있어요<br>옆에서 <b>밀면</b> 떨어져요",
    "tutorial.tool.sniff.1": "할아버지가 <b>밟아!</b>를 가르쳐 줬어요<br>눌러서 시켜 보세요",
    "tutorial.tool.sniff.2": "<b>주변</b> 수풀을 누르면<br>밟아서 길이 돼요",
    "tutorial.tool.dest.1": "할아버지가 <b>점프!</b>를 가르쳐 줬어요<br>눌러서 시켜 보세요",
    "tutorial.tool.dest.2": "<b>내려앉을 땅</b>을 누르면<br>공을 뛰어넘어 거기 내려요",
    "tutorial.tool.order.1": "할아버지가 <b>갖고와!</b>를 가르쳐 줬어요<br>눌러서 시켜 보세요",
    "tutorial.tool.order.2": "<b>주변</b> 공을 누르면<br>물어다 <b>맥스 곁</b>에 놔요",
    "tutorial.matWallHit": "간식이 떨어졌어요!",
    "tutorial.stepLimit": "남은 걸음 안에 공을 방석에 넣어요",
    "tutorial.acornFirst": "길에 간식이 떨어져 있어요<br>밟으면 주워요",
    "tutorial.acornUse": "주운 간식은 상점에서 쓸 수 있어요",
    "tutorial.acornAgain": "두고 온 간식 {n}개<br>다시 걸으면 주울 수 있어요",
    "note.tipMat": "{mat} · {from}에서 나와요",
    "mat.acorn": "간식",
    "tutorial.matCoachBush": "수풀에 걸린 <b>간식</b><br>옆에서 <b>밀면</b> 떨어져요",
    "tutorial.matCoachEdge": "울타리에도 <b>간식</b>이 걸려 있어요<br>여기도 <b>밀어</b> 보세요",
    "tutorial.mealFirst": "<b>일과표</b>가 열렸어요<br>첫 일은 <b>밥 주기</b>예요",
    "tutorial.mealChores": "밥 주기는 <b>하루 세 번</b> 돌아와요<br>수첩 <b>일과표</b>에 적혀 있어요",
    "map.giftTitle": "{lv}번째 산책 꾸러미",
    "map.giftLeft": "안 연 꾸러미 {n}",
    "map.giftOpen": "열기",
    "map.giftCoach": "눌러서 열어 보세요",
    "map.giftAtLv": "{lv}번째 산책에서 열려요",
    "map.giftGot": "받았어요",
    "map.giftAria": "{lv}번째 산책 꾸러미 속 보기",
    "victory.chipMade": "{item} 설계도 완성!",
    "note.bpAuto": "조각 셋이 모이면 저절로 설계도가 돼요",
    "victory.chipMadeSub": "마당 빈 자리에 지을 수 있어요",
    "note.srcAll": "<b>큰 가구</b> 험한 판을 처음 깨면 설계도 한 장 · <b>작은 가구</b> 그 동네 판 10개를 깰 때마다 설계도 한 장",
    "note.lockYard": "맥스 하우스가 완성되면 열려요",
    "note.smallAt": "판 {n} / {t} · {goal}판째에 설계도",
    "growth.shortFrom": "{mat}{particle} {n}개 모자라요 · {places} 판에서 나와요",
    "growth.shortFree": "마당일이 3일마다 간식을 셋씩 줘요",
    "growth.needMore": "{mat} {n}개 더",
    "growth.goBtn": "가기",
    "growth.buyMat": "{mat} {n}개 사기",
    "note.bpNone": "아직 모으는 설계도가 없어요",
    "note.bpDoneRow": "설계도 완성 · 마당 빈 자리에 지어요",
    "note.bpBuildYard": "마당에서 짓기",
    "note.bpYardLater": "{name} 마당이 열리면 지어요",
    "note.bpNoSlot": "놓을 빈 자리가 없어요 — 들른 날이 쌓이면 자리가 늘어요",
    "note.planDone": "다 지었어요",
    "note.planReady": "지을 수 있어요",
    "note.planAt": "다음 설계도 · {lv}번째 산책 꾸러미",
    "note.planBuild": "짓기",
    "note.planDraw": "그리기",
    "note.lockAt": "{n}판 걸으면 열려요",
    "note.lockCase": "장난감을 물어 오면 열려요",
    "note.lockAlbum": "동네 하나를 끝내면 열려요",
    "note.lockBuild": "험한 판을 깨면 열려요",
    "note.stamps": "도장 {n}개",
    "diary.morning": "아침 심부름",
    "diary.evening": "저녁 일과",
    "diary.week": "이번 주",
    "diary.noErrand": "심부름을 준비하고 있어요",
    "diary.moreSoon": "다음 동네를 걸으면 심부름이 더 넓어져요",
    "time.left": "{time} 남음",
    "errand.d1": "마당",
    "errand.d2": "뒷마당",
    "errand.d3": "동산",
    "errand.d4": "공터",
    "errand.d5": "텃밭",
    "errand.d6": "창고",
    "errand.d7": "울타리길",
    "errand.d8": "골목",
    "errand.d9": "냇가",
    "errand.d10": "들판",
    "gift.title": "오늘 몫",
    "gift.pending": "오늘 일과를 마치면 할아버지의 선물이 열려요",
    "gift.ready": "다 걸었어요 — 맥스가 뭔가 물고 왔어요",
    "gift.got": "{what} · 내일 또 물어와요",
    "gift.kibhalf": "사료 반 봉지",
    "settings.audioCredits": "음원 출처",
    "billing.storageUnavailable": "저장 기록을 읽을 수 없어요. 데이터를 지우지 말고 앱을 다시 켜 주세요.",
    "billing.storageFailed": "결제는 확인했지만 저장하지 못했어요. 다시 구매하지 말고 앱을 다시 켜 주세요.",
    "guide.impact": "쿵!",
    "yardTip.house": "밥때가 되면 <b>밥·물그릇</b>에 밥을 채워 주세요<br>하루 세 번 돌아와요",
    "yardTip.colTub": "",
    "yardTip.colTramp": "눌러서 트램플린에 공을 던져요<br>튄 공을 맥스가 물어 와요",
    "yardTip.colOak": "하루 한 번 떨어진 <b>도토리</b>를 주워요<br>동산은 험한 판을 깨면 자라요",
    "yardTip.colDig": "심고 하루 한 번 <b>물</b>을 주세요<br>다 자라면 수확해요",
    "yardTip.colBox": "같은 작물 <b>3개</b>를 보내세요<br>다음 날 답례가 와요",
    "yardTip.colPaint": "하루 한 획 맥스 <b>초상화</b>를 그려요<br>일곱 획이면 한 장 · 그린 뒤엔 마당 물건을 칠해요",
    "yardTip.colCatBed": "<b>밥그릇</b>을 누르면 둘이 와요<br>수수는 <b>지붕 용마루</b>, 율무는 <b>차양</b> 위로",
    "yardTip.colBrook": "하루 한 번 떠내려온 <b>낙엽</b>을 건져요<br>사흘마다 <b>돌</b>이 나와요",
    "yardTip.colPin": "날개에 걸린 것을 <b>떼어</b> 주세요<br>바람이 <b>도토리</b>를 굴려 와요",
    "yardCrop.carrot": "당근",
    "yardCrop.potato": "감자",
    "yardCrop.radish": "무",
    "yardDeco.ball": "공 바구니",
    "yardDeco.hoop": "고리",
    "yardDeco.bunting": "깃발 줄",
    "yardPalette.base": "기본",
    "yardPalette.blue": "파랑",
    "yardPalette.sun": "노랑·초록",
    "yardPalette.rose": "분홍",
    "yardPalette.rain": "무지개",
    "yardPay.carrot": "마중표 1장",
    "yardPay.potato": "사료 1봉",
    "yardPay.radish": "도토리 12",
    "yardStatus.mealDone": "오늘 {count}끼 다 먹었어요",
    "yardStatus.feed": "밥 채우기",
    "yardStatus.mealReady": "오늘 {count} / {max}끼",
    "yardStatus.mealWait": "{time}",
    "yardStatus.bathDone": "오늘 씻었어요",
    "yardStatus.wash": "씻기기",
    "yardStatus.bathReady": "목욕할 시간이에요",
    "yardStatus.walks": "산책 {count} / {max}",
    "yardStatus.replant": "다시 심기",
    "yardStatus.gather": "도토리 줍기",
    "yardStatus.oakDrop": "도토리가 떨어졌어요",
    "yardStatus.oakDone": "오늘은 다 주웠어요",
    "yardStatus.water": "물 주기",
    "yardStatus.oakWater": "목말라요 · 성장 {count} / {max}",
    "yardStatus.oakWait": "성장 {count} / {max}<br>자라기까지 {time}",
    "yardStatus.hop": "폴짝!",
    "yardStatus.play": "공 던지기",
    "yardStatus.playReady": "공을 던져 볼까요?",
    "yardStatus.playDone": "오늘 공놀이는 했어요",
    "yardStatus.decoWait": "<br>{count}일 더 놀면 {name}{particle} 받아요",
    "yardStatus.harvest": "수확하기",
    "yardStatus.ripe": "{name} 수확할 시간이에요",
    "yardStatus.cropWater": "{name} · 성장 {count} / {max}<br>목말라요",
    "yardStatus.plant": "심기",
    "yardStatus.pickCrop": "무엇을 심을까요",
    "yardStatus.cropWait": "{name} · 성장 {count} / {max}<br>자라기까지 {time}",
    "yardStatus.stroke": "한 획 그리기",
    "yardStatus.portReady": "맥스가 포즈를 잡고 기다려요 · {count} / {max}획",
    "yardStatus.unstick": "걸린 것 떼기",
    "yardStatus.pinStuck": "날개에 {name}{particle} 걸렸어요",
    "pin.stuck.kite": "연",
    "pin.stuck.hat": "밀짚모자",
    "pin.stuck.sock": "양말",
    "pin.stuck.sack": "도토리 자루",
    "yardStatus.pickup": "받기",
    "yardStatus.matWait": "{count}일 더 지나면 {name}{particle} 또 얻어요",
    "yardStatus.windReady": "바람이 도토리를 굴려 왔어요",
    "yardStatus.windDone": "오늘 도토리를 받았어요",
    "yardStatus.windWait": "바람이 불면 도토리가 굴러와요",
    "yardStatus.catsHere": "수수와 율무가 쉬어요 · 누르면 달아나요",
    "yardStatus.catsAway": "놀라서 달아났어요 · 곧 돌아와요",
    "yardStatus.rainbow": "{district} 도토리 90개로 무지개 색이 열려요",
    "yardStatus.palette": "{level}에서 {name}이 열려요",
    "yardStatus.paintDone": "색을 다 모았어요 · 아무 때나 바꿔요",
    "yardStatus.collect": "받기",
    "yardStatus.gift": "답례",
    "yardStatus.parcelReady": "택배가 왔어요 · {name}",
    "yardStatus.parcelWait": "답례 도착까지 {time}<br>{reward}",
    "yardStatus.send": "보내기",
    "yardStatus.sendReady": "보낼 작물을 골라 주세요",
    "yardStatus.sendWait": "같은 작물 {max}개를 모아 주세요",
  };
});
